Repository khushi-purwar/WebDev-ProjectKart, pull requests merged in 2022-03, with the labels that each got.

#87 issue #35 weather application not responsive
  15.Weather_Application/Assets/css/style.css
Labels: Level2, GSSOC22

#142 Added Movie Search App
  Movie-Search-App/README.md
  Movie-Search-App/index.html
  Movie-Search-App/preview.png
  Movie-Search-App/script.js
  Movie-Search-App/styles.css
  index.html
Labels: GSSOC22, Level3

#110 2048 game
  25.2048_Game/README.md
  25.2048_Game/index.html
  25.2048_Game/script.js
  25.2048_Game/styles.css
Labels: GSSOC22, Level3

#89 Add Sudoku Solver Game Project
  Sudoku-Solver-Game/README.md
  Sudoku-Solver-Game/index.html
  Sudoku-Solver-Game/scripts/main.js
  Sudoku-Solver-Game/styles/styles.css
Labels: GSSOC22, Level3

#103 Ping Pong Game
  25. Ping Pong Game/image/image1.png
  25. Ping Pong Game/image/image2.png
  25. Ping Pong Game/image/image3.png
  25. Ping Pong Game/index.html
  25. Ping Pong Game/readme.md
  25. Ping Pong Game/script.js
  25. Ping Pong Game/style.css
Labels: GSSOC22, Level3

#112 currency converter
  25. Curruncy Converter/Readme.md
  25. Curruncy Converter/function.js
  25. Curruncy Converter/index.html
  25. Curruncy Converter/style.css
Labels: GSSOC22, Level3

#113 Added Quiz Game app to The WebDev-ProjectKart Repository
  Quiz App/Js/index.js
  Quiz App/README.md
  Quiz App/index.html
  Quiz App/styles/index.css
Labels: GSSOC22, Level3

#125 Added CryptoRush Application
  26.CryptoRush-Application/Cryptoworld/README.md
  26.CryptoRush-Application/Cryptoworld/package-lock.json
  26.CryptoRush-Application/Cryptoworld/package.json
  26.CryptoRush-Application/Cryptoworld/public/favicon.ico
  26.CryptoRush-Application/Cryptoworld/public/index.html
  26.CryptoRush-Application/Cryptoworld/public/logo192.png
  26.CryptoRush-Application/Cryptoworld/public/logo512.png
  26.CryptoRush-Application/Cryptoworld/public/manifest.json
  26.CryptoRush-Application/Cryptoworld/public/robots.txt
  26.CryptoRush-Application/Cryptoworld/src/App.css
  26.CryptoRush-Application/Cryptoworld/src/App.js
  26.CryptoRush-Application/Cryptoworld/src/app/store.js
  26.CryptoRush-Application/Cryptoworld/src/components/CryptoDetails.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Cryptocurrencies.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Exchanges.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Homepage.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Linechart.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Loader.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/Navbar.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/News.jsx
  26.CryptoRush-Application/Cryptoworld/src/components/index.js
  26.CryptoRush-Application/Cryptoworld/src/image/doge.png
  26.CryptoRush-Application/Cryptoworld/src/image/krypto-logo.png
  26.CryptoRush-Application/Cryptoworld/src/image/news.jpg
  26.CryptoRush-Application/Cryptoworld/src/image/shiba.png
  26.CryptoRush-Application/Cryptoworld/src/index.js
  26.CryptoRush-Application/Cryptoworld/src/services/cryptoApi.js
  26.CryptoRush-Application/Cryptoworld/src/services/cryptoNewsApi.js
  26.CryptoRush-Application/Cryptoworld/working Photos of Website/1.JPG
  26.CryptoRush-Application/Cryptoworld/working Photos of Website/2.JPG
  26.CryptoRush-Application/Cryptoworld/working Photos of Website/3.JPG
  26.CryptoRush-Application/Cryptoworld/working Photos of Website/4.JPG
  26.CryptoRush-Application/Cryptoworld/working Photos of Website/5.JPG
Labels: GSSOC22, Level3

#126 New project added
  Calculator/README.md
  Calculator/assets/css/style.css
  Calculator/assets/media/project_demo.mp4
  Calculator/index.html
Labels: GSSOC22, Level3

#133 Google clone added
  25.Google_Clone/assets/css/style.css
  25.Google_Clone/assets/media/favicon.jpg
  25.Google_Clone/assets/media/logo.jpg
  25.Google_Clone/index.html
  25.Google_Clone/readme.md
  25.Google_Clone/script/main.js
  Projects.md
  index.html
Labels: GSSOC22, Level3

#136 Simon Game #62
  Simon-Game/README.md
  Simon-Game/assests/css/styles.css
  Simon-Game/assests/media/Demo1.jpeg
  Simon-Game/assests/media/Demo2.jpeg
  Simon-Game/assests/media/Demo3.jpeg
  Simon-Game/assests/media/sounds/blue.mp3
  Simon-Game/assests/media/sounds/green.mp3
  Simon-Game/assests/media/sounds/red.mp3
  Simon-Game/assests/media/sounds/wrong.mp3
  Simon-Game/assests/media/sounds/yellow.mp3
  Simon-Game/index.html
  Simon-Game/script/index.js
Labels: GSSOC22, Level3

#147 Rock-Paper-Scissor Game (issue-98)
  rock-paper-scissor-game/README.md
  rock-paper-scissor-game/assets/Paper.png
  rock-paper-scissor-game/assets/Rock.png
  rock-paper-scissor-game/assets/Scissors.png
  rock-paper-scissor-game/assets/title.png
  rock-paper-scissor-game/assets/triangle.png
  rock-paper-scissor-game/index.html
  rock-paper-scissor-game/script.js
  rock-paper-scissor-game/styles.css
Labels: GSSOC22, Level3

#146 Adding a Dice Game
  Dice Game/README.MD
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/index.html
  Dice Game/main.js
  Dice Game/styles.css
Labels: GSSOC22, Level3

#148 Remote
  25.Word_Definition/Readme.md
  25.Word_Definition/assets/css/style.css
  25.Word_Definition/index.html
  25.Word_Definition/script/app.js
Labels: GSSOC22, Level3

#152 Added a new project Drum Kit Online
  30.Drum-Kit/README.md
  30.Drum-Kit/images/crash.png
  30.Drum-Kit/images/kick.png
  30.Drum-Kit/images/snare.png
  30.Drum-Kit/images/tom1.png
  30.Drum-Kit/images/tom2.png
  30.Drum-Kit/images/tom3.png
  30.Drum-Kit/images/tom4.png
  30.Drum-Kit/index.html
  30.Drum-Kit/index.js
  30.Drum-Kit/sounds/crash.mp3
  30.Drum-Kit/sounds/kick-bass.mp3
  30.Drum-Kit/sounds/snare.mp3
  30.Drum-Kit/sounds/tom-1.mp3
  30.Drum-Kit/sounds/tom-2.mp3
  30.Drum-Kit/sounds/tom-3.mp3
  30.Drum-Kit/sounds/tom-4.mp3
  30.Drum-Kit/styles.css
  index.html
Labels: GSSOC22, Level3

#153 Added Color Flipper
  Color Flipper/index.html
  Color Flipper/sond.js
  Color Flipper/sondi.css
Labels: GSSOC22, Level3

#155 Breakout Game files added
  Breakout_Game/index.html
  Breakout_Game/script.js
  Breakout_Game/style.css
  index.html
Labels: GSSOC22, Level3

#156 Pokemon Generator files added
  Pokemon Generator/index.html
  Pokemon Generator/script.js
  Pokemon Generator/style.css
  index.html
Labels: GSSOC22, Level3

#157 Tic Tac Toe files added
  Tic-Tac-Toe/index.html
  Tic-Tac-Toe/script.js
  Tic-Tac-Toe/style.css
  index.html
Labels: GSSOC22, Level3

#161 added keep notes app
  Google_Keep_Notes_Clone/.gitignore
  Google_Keep_Notes_Clone/README.md
  Google_Keep_Notes_Clone/package-lock.json
  Google_Keep_Notes_Clone/package.json
  Google_Keep_Notes_Clone/public/index.html
  Google_Keep_Notes_Clone/public/manifest.json
  Google_Keep_Notes_Clone/public/robots.txt
  Google_Keep_Notes_Clone/src/App.js
  Google_Keep_Notes_Clone/src/CreateNote.js
  Google_Keep_Notes_Clone/src/Footer.js
  Google_Keep_Notes_Clone/src/Header.js
  Google_Keep_Notes_Clone/src/Note.js
  Google_Keep_Notes_Clone/src/index.js
  Google_Keep_Notes_Clone/src/style.css
Labels: GSSOC22, Level3

#163 Added Login form with captcha feature
  LoginForm/.gitignore
  LoginForm/index.html
  LoginForm/package-lock.json
  LoginForm/script.js
  LoginForm/style.css
Labels: GSSOC22, Level3

#164 File Upload App added
  .DS_Store
  File Upload/.DS_Store
  File Upload/index.html
  File Upload/script.js
  File Upload/style.css
  index.html
Labels: GSSOC22, Level3

#160 Camera-Booth with Filters added
  Camera-Booth_with_Filters/Assets/css/style.css
  Camera-Booth_with_Filters/Assets/media/Click!.jpeg
  Camera-Booth_with_Filters/Assets/media/snap.mp3
  Camera-Booth_with_Filters/README.md
  Camera-Booth_with_Filters/index.html
  Camera-Booth_with_Filters/script/scripts.js
Labels: GSSOC22, Level3

#174 Improved Weather App
  15.Weather_Application/.vscode/settings.json
  15.Weather_Application/Assets/css/style.css
  15.Weather_Application/Weather-App.jpg
  15.Weather_Application/index.html
  15.Weather_Application/readme.md
  15.Weather_Application/script.js
  15.Weather_Application/script/script.js
  15.Weather_Application/style.css
Labels: Level2, GSSOC22

#150 Code enhance in Random gradient color
  21.Random_grediant_color/assets/css/style.css
  21.Random_grediant_color/index.html
  21.Random_grediant_color/script/index.js
Labels: Level2, GSSOC22

#120 Fixes issue #67
  01.Password_Generator/Assets/css/style.css
  01.Password_Generator/index.html
Labels: Level2, GSSOC22

#165 Hover effect
  style.css
Labels: Level2, GSSOC22

#177 Update PULL_REQUEST_TEMPLATE.md
  .docs/PULL_REQUEST_TEMPLATE.md
Labels: Level1, GSSOC22

#106 [Bugfixed] Readme.md
  README.md
Labels: Level1, GSSOC22

#188 Added Maze Game Project
  34.Maze-Game/css/style.css
  34.Maze-Game/index.html
  34.Maze-Game/js/index.js
  index.html
Labels: GSSOC22, Level3

#200 Color code conv
  Color_Code_Converter/assets/css/style.css
  Color_Code_Converter/assets/media/Capture.PNG
  Color_Code_Converter/index.html
  Color_Code_Converter/readme.md
  Color_Code_Converter/scripts/app.js
Labels: GSSOC22, Level3

#193 improve stopwatch
  18.Stopwatch_App/Assets/css/style.css
  18.Stopwatch_App/index.html
  18.Stopwatch_App/script/script.js
Labels: Level2, GSSOC22

#167 Neumorphic power button
  Neumorphic-power-button/README.md
  Neumorphic-power-button/index.html
  Neumorphic-power-button/style.css
Labels: GSSOC22, Level3

#168 Neumorphism Login and Register Page
  Login - Register-Neumorphic/index.html
  Login - Register-Neumorphic/logo.png
  Login - Register-Neumorphic/signUp.html
  Login - Register-Neumorphic/style.css
Labels: GSSOC22, Level3

#184 Added : Word Counter Project
  Word Counter/Readme.md
  Word Counter/index.html
  Word Counter/javascript/javas.js
  Word Counter/snip.png
  Word Counter/style/style.css
Labels: GSSOC22, Level3

#185 Added Tenzies Game. A fun dice game.
  25. Tenzies game/README.md
  25. Tenzies game/Screenshot (103).png
  25. Tenzies game/Screenshot (104).png
  25. Tenzies game/Screenshot (106).png
  25. Tenzies game/package-lock.json
  25. Tenzies game/package.json
  25. Tenzies game/public/dice.png
  25. Tenzies game/public/index.html
  25. Tenzies game/public/manifest.json
  25. Tenzies game/public/robots.txt
  25. Tenzies game/src/App.js
  25. Tenzies game/src/Die.js
  25. Tenzies game/src/index.css
  25. Tenzies game/src/index.js
Labels: GSSOC22, Level3

#209 Added random jokes
  Random Jokes/README.md
  Random Jokes/assests/css/styles.css
  Random Jokes/assests/media/bgImage.jfif
  Random Jokes/index.html
  Random Jokes/script/script.js
Labels: GSSOC22, Level3

#210 Add favicon to website
  favicon/favicon.ico
  index.html
Labels: Level1, GSSOC22

#219 GitHub profile project 218
  GitHub Profiles/README.md
  GitHub Profiles/index.html
  GitHub Profiles/script.js
  GitHub Profiles/style.css
Labels: GSSOC22, Level3

#211 add 12hour and 24hour functionality plus responsive
  05.Digital_Clock/Assets/css/style.css
  05.Digital_Clock/Assets/media/ssUpdated.png
  05.Digital_Clock/index.html
  05.Digital_Clock/script/script.js
Labels: Level2, GSSOC22

#181 Sneaker site files added
  Sneaker Site/img/air.png
  Sneaker Site/img/air2.png
  Sneaker Site/img/blazer.png
  Sneaker Site/img/blazer2.png
  Sneaker Site/img/contact.png
  Sneaker Site/img/crater.png
  Sneaker Site/img/crater2.png
  Sneaker Site/img/facebook.png
  Sneaker Site/img/gift.png
  Sneaker Site/img/hippie.png
  Sneaker Site/img/hippie2.png
  Sneaker Site/img/instagram.png
  Sneaker Site/img/jordan.png
  Sneaker Site/img/jordan2.png
  Sneaker Site/img/master.png
  Sneaker Site/img/return.png
  Sneaker Site/img/search.png
  Sneaker Site/img/shipping.png
  Sneaker Site/img/sneakers.png
  Sneaker Site/img/twitter.png
  Sneaker Site/img/visa.png
  Sneaker Site/img/whatsapp.png
  Sneaker Site/index.html
  Sneaker Site/script.js
  Sneaker Site/styles.css
  index.html
Labels: GSSOC22, Level3

#191 Added Rock Paper Scissors Game
  36.Rock-Paper-Scissors/Paper.png
  36.Rock-Paper-Scissors/Rock.png
  36.Rock-Paper-Scissors/Scissors.png
  36.Rock-Paper-Scissors/index.html
  36.Rock-Paper-Scissors/script.js
  36.Rock-Paper-Scissors/style.css
  index.html
Labels: GSSOC22, Level3

#197 Added Color Picker Game
  Color Picker Game/Assets/css/style.css
  Color Picker Game/Assets/media/Output.PNG
  Color Picker Game/README.md
  Color Picker Game/Script/delete.html
  Color Picker Game/Script/script.js
  Color Picker Game/index.html
Labels: GSSOC22, Level3

#206 Added CRUD PROJECT
  CRUD_Project/README.md
  CRUD_Project/assets/style.css
  CRUD_Project/index.html
  CRUD_Project/script/script.js
Labels: GSSOC22, Level3

#217 Added Grocery site
  Grocery store/assets/css/style.css
  Grocery store/assets/media.css/Img/banner-1.jpg
  Grocery store/assets/media.css/Img/banner-2.jpg
  Grocery store/assets/media.css/Img/category-1.png
  Grocery store/assets/media.css/Img/category-2.png
  Grocery store/assets/media.css/Img/category-3.png
  Grocery store/assets/media.css/Img/category-4.png
  Grocery store/assets/media.css/Img/deal-bg.jpg
  Grocery store/assets/media.css/Img/deal-img2.png
  Grocery store/assets/media.css/Img/home-img.png
  Grocery store/assets/media.css/Img/newsletter-bg.jpg
  Grocery store/assets/media.css/Img/product-1.png
  Grocery store/assets/media.css/Img/product-2.png
  Grocery store/assets/media.css/Img/product-3.png
  Grocery store/assets/media.css/Img/product-4.png
  Grocery store/assets/media.css/Img/product-5.png
  Grocery store/assets/media.css/Img/product-6.png
  Grocery store/assets/media.css/Img/product-7.png
  Grocery store/assets/media.css/Img/product-8.png
  Grocery store/assets/media.css/Img/product-9.png
  Grocery store/index.html
  Grocery store/script/script.js
Labels: GSSOC22, Level3

#232 Added BaseX Calculator files
  BaseX_Calculator/assets/css/style.css
  BaseX_Calculator/assets/media/capture.png
  BaseX_Calculator/index.html
  BaseX_Calculator/readme.md
  BaseX_Calculator/scripts/app.js
Labels: GSSOC22, Level3

#237 Added Google sheets Api Integration
  Bubble Popping Game/README.md
  Bubble Popping Game/assets/css/style.css
  Bubble Popping Game/assets/js/script.js
  Bubble Popping Game/assets/screenshots/game.JPG
  Bubble Popping Game/assets/screenshots/project.JPG
  Bubble Popping Game/index.html
  Google Sheets Api/README.md
  Google Sheets Api/assets/css/style.css
  Google Sheets Api/assets/js/script.js
  Google Sheets Api/assets/screenshorts/1.JPG
  Google Sheets Api/assets/screenshorts/2.JPG
  Google Sheets Api/config.js
  Google Sheets Api/index.html
Labels: GSSOC22, Level3

#207 Added Bubble Popping Game
  Bubble Popping Game/README.md
  Bubble Popping Game/assets/css/style.css
  Bubble Popping Game/assets/js/script.js
  Bubble Popping Game/assets/screenshots/game.JPG
  Bubble Popping Game/assets/screenshots/project.JPG
  Bubble Popping Game/index.html
Labels: GSSOC22

#238 Improved UI of Stopwatch app
  18.Stopwatch_App/Assets/css/style.css
  18.Stopwatch_App/index.html
  18.Stopwatch_App/script/script.js
Labels: Level2, GSSOC22

#239 Completed the issue #172 under GssoC22
  Digital-clock/README.md
  Digital-clock/clock.html
  Digital-clock/clock.jpg
  Digital-clock/style.css
Labels: GSSOC22, Level3

#227 Add tic tac toe online multiplayer
  Tic-Tac-Toe-Multiplayer/package-lock.json
  Tic-Tac-Toe-Multiplayer/package.json
  Tic-Tac-Toe-Multiplayer/public/css/index.css
  Tic-Tac-Toe-Multiplayer/public/css/room.css
  Tic-Tac-Toe-Multiplayer/public/js/index.js
  Tic-Tac-Toe-Multiplayer/public/js/room.js
  Tic-Tac-Toe-Multiplayer/server.js
  Tic-Tac-Toe-Multiplayer/views/index.ejs
  Tic-Tac-Toe-Multiplayer/views/room.ejs
Labels: GSSOC22, Level3

#242 Added To-do app
  TO-DO App/README.md
  TO-DO App/assests/background.jpg
  TO-DO App/assests/style.css
  TO-DO App/index.html
  TO-DO App/script/script.js
Labels: GSSOC22, Level3

#212 Added GST calculator files.
  02.BMI_Calculator/Assets/css/style.css
  05.Digital_Clock/Assets/css/style.css
  GST calculator/css/index.css
  GST calculator/index.html
  GST calculator/script/index.js
Labels: GSSOC22, Level3

#192 I have uploaded all the required files in this.
  Counter/Readme.md
  Counter/css/styles.css
  Counter/faviconio-logo/about.txt
  Counter/faviconio-logo/logo.png
  Counter/faviconio-logo/logo.svg
  Counter/index.html
  Counter/output1.jpeg
  Counter/script.js
Labels: GSSOC22, Level3

#229 <Added project file Windows 11 Clone>
  02.BMI_Calculator/readme.md
  Windows 11 Clone/Assets/media/A.png
  Windows 11 Clone/Assets/media/B.png
  Windows 11 Clone/Assets/media/C.png
  Windows 11 Clone/Assets/media/D.png
  Windows 11 Clone/Assets/media/Screenshot1.png
  Windows 11 Clone/Assets/media/bg2.jpg
  Windows 11 Clone/Assets/media/chrome.png
  Windows 11 Clone/Assets/media/demo.gif
  Windows 11 Clone/Assets/media/edge.png
  Windows 11 Clone/Assets/media/favicon.ico
  Windows 11 Clone/Assets/media/icons (4).PNG
  Windows 11 Clone/Assets/media/icons (6).PNG
  Windows 11 Clone/Assets/media/icons (7).PNG
  Windows 11 Clone/Assets/media/icons.PNG
  Windows 11 Clone/Assets/media/recyclebinicon.png
  Windows 11 Clone/Assets/media/screen-recording.webm
  Windows 11 Clone/Assets/media/search.png
  Windows 11 Clone/Assets/media/searchIcon.PNG
  Windows 11 Clone/Assets/media/startmenu.png
  Windows 11 Clone/Assets/media/storeIcon.PNG
  Windows 11 Clone/Assets/media/taskbarright.PNG
  Windows 11 Clone/Assets/media/thispc.png
  Windows 11 Clone/Assets/media/vlc.png
  Windows 11 Clone/Assets/media/widgetsIcon.PNG
  Windows 11 Clone/Assets/media/win.PNG
  Windows 11 Clone/Windows 11/Assets/media/A.png
  Windows 11 Clone/Windows 11/Assets/media/B.png
  Windows 11 Clone/Windows 11/Assets/media/C.png
  Windows 11 Clone/Windows 11/Assets/media/D.png
  Windows 11 Clone/Windows 11/Assets/media/Screenshot1.png
  Windows 11 Clone/Windows 11/Assets/media/bg2.jpg
  Windows 11 Clone/Windows 11/Assets/media/chrome.png
  Windows 11 Clone/Windows 11/Assets/media/demo.gif
  Windows 11 Clone/Windows 11/Assets/media/edge.png
  Windows 11 Clone/Windows 11/Assets/media/favicon.ico
  Windows 11 Clone/Windows 11/Assets/media/icons (4).PNG
  Windows 11 Clone/Windows 11/Assets/media/icons (6).PNG
  Windows 11 Clone/Windows 11/Assets/media/icons (7).PNG
  Windows 11 Clone/Windows 11/Assets/media/icons.PNG
  Windows 11 Clone/Windows 11/Assets/media/recyclebinicon.png
  Windows 11 Clone/Windows 11/Assets/media/screen-recording.webm
  Windows 11 Clone/Windows 11/Assets/media/search.png
  Windows 11 Clone/Windows 11/Assets/media/searchIcon.PNG
  Windows 11 Clone/Windows 11/Assets/media/startmenu.png
  Windows 11 Clone/Windows 11/Assets/media/storeIcon.PNG
  Windows 11 Clone/Windows 11/Assets/media/taskbarright.PNG
  Windows 11 Clone/Windows 11/Assets/media/thispc.png
  Windows 11 Clone/Windows 11/Assets/media/vlc.png
  Windows 11 Clone/Windows 11/Assets/media/widgetsIcon.PNG
  Windows 11 Clone/Windows 11/Assets/media/win.PNG
  Windows 11 Clone/Windows 11/index.html
  Windows 11 Clone/Windows 11/readme.md
  Windows 11 Clone/Windows 11/script/script.js
  Windows 11 Clone/Windows 11/style.css
  Windows 11 Clone/index.html
  Windows 11 Clone/readme.md
  Windows 11 Clone/script/script.js
  Windows 11 Clone/style.css
Labels: GSSOC22, Level3

#248 Fixes Issue #204
  GST_Calculator/design.css
  GST_Calculator/index.html
  GST_Calculator/readme.md
  GST_Calculator/script.js
Labels: GSSOC22, Level3

#255 Dictionary Files added
  Candy Crush/candy-crush-background.png
  Candy Crush/images/blue-candy.png
  Candy Crush/images/green-candy.png
  Candy Crush/images/orange-candy.png
  Candy Crush/images/purple-candy.png
  Candy Crush/images/red-candy.png
  Candy Crush/images/yellow-candy.png
  Candy Crush/index.html
  Candy Crush/script.js
  Candy Crush/styles.css
  Customize-Ice-Cream/index.html
  Customize-Ice-Cream/script.js
  Customize-Ice-Cream/styles.css
  Dictionary App/index.html
  Dictionary App/script.js
  Dictionary App/styles.css
  Pong Game/Ball.js
  Pong Game/Paddle.js
  Pong Game/index.html
  Pong Game/script.js
  Pong Game/styles.css
  index.html
Labels: GSSOC22, Level3

#258 Changes done according to the issue raised.
  09.Quote_Generator/Assets/css/style.css
  09.Quote_Generator/index.html
Labels: Level2, GSSOC22

#256 Added GSSoC logo under 'This project was part of...' section in readme
  README.md
  images/gssoc.png
Labels: Level1, GSSOC22

#259 Model Window
  ModelWindow/.prettierrc
  ModelWindow/index.html
  ModelWindow/script.js
  ModelWindow/style.css
Labels: GSSOC22, Level3

#270 Added Random Anime profile pic generator to the list
  Anime profiles/README.md
  Anime profiles/index.html
  Anime profiles/js/script.js
  Anime profiles/styles/style.css
Labels: GSSOC22, Level3

#276 Rd calculator
  RD return calculator/index.html
  RD return calculator/readme.md
  RD return calculator/script.js
  RD return calculator/style.css
Labels: GSSOC22, Level3

#279 Clock improvement
  05.Digital_Clock/Assets/css/style.css
  05.Digital_Clock/Assets/media/SS.jpg
  05.Digital_Clock/Assets/media/ss1.png
  05.Digital_Clock/index.html
  05.Digital_Clock/readme.md
  05.Digital_Clock/script/script.js
Labels: Level2, GSSOC22

#292 Palindrome checker
  37.Palindrome_Checker/README.md
  37.Palindrome_Checker/index.html
  37.Palindrome_Checker/script.js
  37.Palindrome_Checker/style.css
  index.html
Labels: GSSOC22, Level3

#294 branch_first
  08.Calculator/Assets/css/style.css
  08.Calculator/index.html
  08.Calculator/script/script.js
Labels: Level2, GSSOC22

#264 whack a mole game
  whack a mole game/README.md
  whack a mole game/dirt.svg
  whack a mole game/index.html
  whack a mole game/index.js
  whack a mole game/mole.svg
  whack a mole game/style.css
Labels: GSSOC22, Level3

#244 flip Effect #223
  flip_card1/img/img1.png
  flip_card1/index.html
  flip_card1/style.css
Labels: Level2, GSSOC22

#246 Create YouTube Video Downloader
  Youtube-Video-Downloader-App/app.js
  Youtube-Video-Downloader-App/package-lock.json
  Youtube-Video-Downloader-App/package.json
  Youtube-Video-Downloader-App/public/index.css
  Youtube-Video-Downloader-App/public/index.html
  Youtube-Video-Downloader-App/public/index.js
Labels: GSSOC22, Level3

#298 Added Sample Product Landing Page
  Sample Product Landing Page/Assets/css/index.css
  Sample Product Landing Page/index.html
  Sample Product Landing Page/readme.md
Labels: GSSOC22, Level3

#300 Added fingerprint scanner animation
  fingerprint scanning animation/README.md
  fingerprint scanning animation/fingerPrint_01.png
  fingerprint scanning animation/fingerPrint_02.png
  fingerprint scanning animation/index.html
  fingerprint scanning animation/style.css
Labels: GSSOC22, Level3

#304 issue-303-fixed
  Candy-Crush-Game/Final-Background.jpg
  Candy-Crush-Game/README.md
  Candy-Crush-Game/app.js
  Candy-Crush-Game/candy-crush-background-2.png
  Candy-Crush-Game/images/blue-candy.png
  Candy-Crush-Game/images/green-candy.png
  Candy-Crush-Game/images/orange-candy.png
  Candy-Crush-Game/images/purple-candy.png
  Candy-Crush-Game/images/red-candy.png
  Candy-Crush-Game/images/yellow-candy.png
  Candy-Crush-Game/index.html
  Candy-Crush-Game/style.css
Labels: GSSOC22, Level3

#313 added ping-pong game
  ping-pong game/ball.js
  ping-pong game/index.html
  ping-pong game/paddle.js
  ping-pong game/readme.md
  ping-pong game/script.js
  ping-pong game/styles.css
Labels: GSSOC22, Level3

#315 Added Random Emoji Generator
  Random Emoji Generator/.gitignore
  Random Emoji Generator/README.md
  Random Emoji Generator/package-lock.json
  Random Emoji Generator/package.json
  Random Emoji Generator/public/index.html
  Random Emoji Generator/public/manifest.json
  Random Emoji Generator/public/robots.txt
  Random Emoji Generator/src/App.css
  Random Emoji Generator/src/App.js
  Random Emoji Generator/src/App.test.js
  Random Emoji Generator/src/Components/home.jsx
  Random Emoji Generator/src/index.css
  Random Emoji Generator/src/index.js
  Random Emoji Generator/src/logo.svg
  Random Emoji Generator/src/reportWebVitals.js
  Random Emoji Generator/src/setupTests.js
Labels: GSSOC22, Level3

#319 Project Added: Youtube clone
  .DS_Store
  Youtube-Clone/.DS_Store
  Youtube-Clone/404.html
  Youtube-Clone/README.md
  Youtube-Clone/Resources/favicon_32x32.png
  Youtube-Clone/Resources/youtube_logo.png
  Youtube-Clone/Resources/youtube_logo.webp
  Youtube-Clone/css/styles.css
  Youtube-Clone/index.html
  Youtube-Clone/script.js
Labels: GSSOC22, Level3

#321 Added Tribute Page
  Tribute Page/Assets/css/style.css
  Tribute Page/page.html
  Tribute Page/readme.md
Labels: GSSOC22, Level3

#323 Added Discord App Clone Files
  Discord_App_Clone/assets/css/bootstrap.css
  Discord_App_Clone/assets/css/bootstrap.css.map
  Discord_App_Clone/assets/css/style.css
  Discord_App_Clone/assets/media/FriendsImages/Avatar0.png
  Discord_App_Clone/assets/media/FriendsImages/Avatar1.png
  Discord_App_Clone/assets/media/ServersCol/GSSoC_Server.webp
  Discord_App_Clone/assets/media/ServersCol/Server0.webp
  Discord_App_Clone/assets/media/ServersCol/Server1.webp
  Discord_App_Clone/assets/media/ServersCol/discord_server_icon.png
  Discord_App_Clone/assets/media/Tab_Icon.svg
  Discord_App_Clone/home.html
  Discord_App_Clone/scripts/bootstrap.bundle.js
  Discord_App_Clone/scripts/bootstrap.bundle.js.map
Labels: GSSOC22, Level3

#310 IP Tracker added
  38.IP-Address Tracker/Readme.md
  38.IP-Address Tracker/design.css
  38.IP-Address Tracker/index.html
Labels: GSSOC22, Level3

#306 Added Background generator project
  Background Generator/README.md
  Background Generator/index.html
  Background Generator/script.js
  Background Generator/style.css
  CSS Grid/Grid cheatsheet.txt
  CSS Grid/index.html
  CSS Grid/style.css
Labels: GSSOC22, Level3

#328 Random User Generator
  Random User Generator/README.md
  Random User Generator/css/style.css
  Random User Generator/img/add-read.png
  Random User Generator/img/ss1.jpg
  Random User Generator/img/ss2.jpg
  Random User Generator/index.html
  Random User Generator/js/app.js
Labels: GSSOC22, Level3

#326 Added Survey Form Project
  Survey Form/Assets/css/index.css
  Survey Form/index.html
  Survey Form/readme.md
  Survey Form/script/index.js
Labels: GSSOC22, Level3

#309 MarioInWonderland-game
  Mario In Wonderland-Game/README.md
  Mario In Wonderland-Game/assets/css/style.css
  Mario In Wonderland-Game/assets/media/back.mp3
  Mario In Wonderland-Game/assets/media/bg2.jpg
  Mario In Wonderland-Game/assets/media/gameover.wav
  Mario In Wonderland-Game/assets/media/mario.png
  Mario In Wonderland-Game/assets/media/zombie.png
  Mario In Wonderland-Game/index.html
  Mario In Wonderland-Game/script/script.js
Labels: GSSOC22, Level3

#329 Catch Me If You Can game
  Catch_Me_If_You_Can/README.md
  Catch_Me_If_You_Can/index.html
  Catch_Me_If_You_Can/script.js
  Catch_Me_If_You_Can/style.css
Labels: GSSOC22, Level3

#336 Added Starbucks clone
  Starbucks clone/index.html
  Starbucks clone/previewstarbucks.png
  Starbucks clone/readme.md
  Starbucks clone/starbucks img 1.png
  Starbucks clone/starbucks img 10.png
  Starbucks clone/starbucks img 2.png
  Starbucks clone/starbucks img 3.png
  Starbucks clone/starbucks img 4.png
  Starbucks clone/starbucks img 5.png
  Starbucks clone/starbucks img 6.png
  Starbucks clone/starbucks img 7.png
  Starbucks clone/starbucks main logo.png
  Starbucks clone/style.css
Labels: GSSOC22, Level3

#338 Added Website Layout
  Layout/.DS_Store
  Layout/README.md
  Layout/img/data_storage_2_2.png
  Layout/img/desktop_analytics_2.png
  Layout/img/files_2.png
  Layout/img/monitor_coding_2.png
  Layout/img/monitor_settings_2.png
  Layout/img/server_2_2.png
  Layout/img/server_3.png
  Layout/img/server_safe_2.png
  Layout/img/undraw.png
  Layout/index.html
  Layout/style.css
Labels: GSSOC22, Level3

#345 Added image slider
  image_slider_using_javascript/README.md
  image_slider_using_javascript/app.js
  image_slider_using_javascript/desktop.ini
  image_slider_using_javascript/images/a.jpg
  image_slider_using_javascript/images/b.jpg
  image_slider_using_javascript/images/c.jpg
  image_slider_using_javascript/images/d.jpg
  image_slider_using_javascript/images/e.jpg
  image_slider_using_javascript/index.html
  image_slider_using_javascript/style.css
Labels: GSSOC22, Level3

#343 Added my portfolio website created with HTML CSS and JavaScript..
  AmolShelke-Portfolio/Js/script.js
  AmolShelke-Portfolio/README.md
  AmolShelke-Portfolio/assets/GithubUser.png
  AmolShelke-Portfolio/assets/anime.png
  AmolShelke-Portfolio/assets/developerActivity.a41f7848.svg
  AmolShelke-Portfolio/assets/home-banner__illust.svg
  AmolShelke-Portfolio/assets/icon.jpeg
  AmolShelke-Portfolio/assets/productLanding.png
  AmolShelke-Portfolio/assets/responsiveWeb.png
  AmolShelke-Portfolio/assets/weather.png
  AmolShelke-Portfolio/index.html
  AmolShelke-Portfolio/styles/style.css
Labels: GSSOC22, Level3

#346 Added amazon prime video page clone
  Amazon_prime_video_login_page_clone/README.md
  Amazon_prime_video_login_page_clone/index.css
  Amazon_prime_video_login_page_clone/index.html
Labels: GSSOC22, Level3

#349 Added Cubic_eq_solver files
  Function_Plotter/assets/css/bootstrap.css
  Function_Plotter/assets/css/bootstrap.css.map
  Function_Plotter/assets/css/style.css
  Function_Plotter/assets/media/function_plotter.png
  Function_Plotter/index.html
  Function_Plotter/readme.md
  Function_Plotter/scripts/app.js
  Function_Plotter/scripts/bootstrap.bundle.js
  Function_Plotter/scripts/bootstrap.bundle.js.map
  Function_Plotter/scripts/function_plot.js
Labels: GSSOC22, Level3

#352 Light Bulb
  Light Bulb/README.md
  Light Bulb/css/style.css
  Light Bulb/img/add-readme.png
  Light Bulb/img/bulb_off.jpg
  Light Bulb/img/bulb_on.jpg
  Light Bulb/img/off.jpg
  Light Bulb/img/on.jpg
  Light Bulb/index.html
Labels: GSSOC22, Level3

#353 some changes // image in readme file are seen clearly
  README.md
  khushipic.jpg
Labels: Level1, GSSOC22

#355 Added Snake Game
  Snake-Game/README.md
  Snake-Game/Snake-Game.png
  Snake-Game/images/apple1.png
  Snake-Game/images/mango.png
  Snake-Game/images/pear.png
  Snake-Game/images/wp2409705.jpg
  Snake-Game/index.html
  Snake-Game/script.js
  Snake-Game/style.css
Labels: GSSOC22, Level3

#350 Updated : Readme
  README.md
Labels: Level1, GSSOC22

#364 Added spinning wheel game
  Spinning Wheel Game/README.md
  Spinning Wheel Game/index.html
  Spinning Wheel Game/script.js
  Spinning Wheel Game/style.css
Labels: GSSOC22, Level3

#373 WebD Project Completed
  CreativeAgencyWebsite/contact.html
  CreativeAgencyWebsite/css/style.css
  CreativeAgencyWebsite/images/001.png
  CreativeAgencyWebsite/images/002.png
  CreativeAgencyWebsite/images/003.png
  CreativeAgencyWebsite/images/004.png
  CreativeAgencyWebsite/images/005.png
  CreativeAgencyWebsite/images/006.png
  CreativeAgencyWebsite/images/address.png
  CreativeAgencyWebsite/images/call.png
  CreativeAgencyWebsite/images/close.png
  CreativeAgencyWebsite/images/email.png
  CreativeAgencyWebsite/images/email2.png
  CreativeAgencyWebsite/images/facebook.png
  CreativeAgencyWebsite/images/home-img.jpg
  CreativeAgencyWebsite/images/img1.jpg
  CreativeAgencyWebsite/images/instagram.png
  CreativeAgencyWebsite/images/menu.png
  CreativeAgencyWebsite/images/portfolio-item1.jpg
  CreativeAgencyWebsite/images/portfolio-item10.jpg
  CreativeAgencyWebsite/images/portfolio-item11.jpg
  CreativeAgencyWebsite/images/portfolio-item12.jpg
  CreativeAgencyWebsite/images/portfolio-item13.jpg
  CreativeAgencyWebsite/images/portfolio-item14.jpg
  CreativeAgencyWebsite/images/portfolio-item15.jpg
  CreativeAgencyWebsite/images/portfolio-item16.jpg
  CreativeAgencyWebsite/images/portfolio-item2.jpg
  CreativeAgencyWebsite/images/portfolio-item3.jpg
  CreativeAgencyWebsite/images/portfolio-item4.jpg
  CreativeAgencyWebsite/images/portfolio-item5.jpg
  CreativeAgencyWebsite/images/portfolio-item6.jpg
  CreativeAgencyWebsite/images/portfolio-item7.jpg
  CreativeAgencyWebsite/images/portfolio-item8.jpg
  CreativeAgencyWebsite/images/portfolio-item9.jpg
  CreativeAgencyWebsite/images/screenshot.png
  CreativeAgencyWebsite/images/twitter.png
  CreativeAgencyWebsite/index.html
  CreativeAgencyWebsite/js/script.js
  CreativeAgencyWebsite/services.html
  CreativeAgencyWebsite/work.html
Labels: GSSOC22, Level3

#357 Added Timeline
  Timeline/README.md
  Timeline/index.html
  Timeline/style.css
Labels: GSSOC22, Level3

#356 Temperature converter
  Temperature_Converter/css/normalize.css
  Temperature_Converter/css/reset.css
  Temperature_Converter/css/style.css
  Temperature_Converter/img/temperature-icon.png
  Temperature_Converter/index.html
  Temperature_Converter/js/main.js
Labels: GSSOC22, Level3

#288 case converter added
  Case-Converter/index.html
  Case-Converter/readme.md
  Case-Converter/script/App.js
  Case-Converter/style/style.css
  index.html
Labels: GSSOC22, Level3

#274 Editing the Home page
  images/Random_gradient.jpg
  images/Simple Quiz.jpg
  images/analog_clock.jpg
  images/battery.jpg
  images/bmi calculator.jpg
  images/breakout_game.jpg
  images/calculator.jpg
  images/coin_toss.jpg
  images/contact_us.jpg
  images/digital_clock.jpg
  images/drawing_app.jpg
  images/drum_kit.jpg
  images/event_counter.jpg
  images/file_upload.jpg
  images/google_clone.jpg
  images/headlines.jpg
  images/loan_calculator.jpg
  images/maze_game.jpg
  images/movie_search.jpg
  images/number_guess.jpg
  images/olor_scheme.jpg
  images/password generaotr.jpg
  images/pokemon_game.jpg
  images/quote_generator.jpg
  images/rock_paper.jpg
  images/sneakers_site.jpg
  images/stopwatch.jpg
  images/thumbnail.png
  images/tic_tac_toe.jpg
  images/tip_calculator.jpg
  images/todo.jpg
  images/vat_calculator.jpg
  images/weather_app.jpg
  index.html
  style.css
Labels: Level2, GSSOC22

#374 Added Todo Shopping List
  Shopping List/README.md
  Shopping List/index.html
  Shopping List/script.js
  Shopping List/style.css
Labels: GSSOC22, Level3

#377 Added Colorful Rain Effect
  Colorful_Rain_Effect/.vscode/settings.json
  Colorful_Rain_Effect/index.html
  Colorful_Rain_Effect/readme.md
  Colorful_Rain_Effect/style.css
  README.md
  index.html
Labels: GSSOC22, Level3

#378 Simple UI clone of Cabify website. (reference to issue #351)
  UI Clone of Cabify website/UI.png
  UI Clone of Cabify website/assets/app.jpg
  UI Clone of Cabify website/assets/driver.jpg
  UI Clone of Cabify website/assets/group.jpg
  UI Clone of Cabify website/index.html
  UI Clone of Cabify website/main.js
Labels: GSSOC22, Level3

#158 Score Keeper App added
  29.Score-Keeper-App/app.js
  29.Score-Keeper-App/demo.gif
  29.Score-Keeper-App/demo.png
  29.Score-Keeper-App/demo1.png
  29.Score-Keeper-App/index.html
  29.Score-Keeper-App/style.css
  index.html
Labels: GSSOC22, Level3

#257 Final Commit
  Unit Conversion/README.md
  Unit Conversion/calculation.js
  Unit Conversion/display.js
  Unit Conversion/index.html
  Unit Conversion/style.css
Labels: GSSOC22

#368 Love Calculator
  Love Calculator/README.md
  Love Calculator/css/style.css
  Love Calculator/img/add-readme (1).png
  Love Calculator/img/sc-1.jpeg
  Love Calculator/img/sc-2.jpeg
  Love Calculator/index.html
  Love Calculator/js/app.js
Labels: GSSOC22, Level3

#381 Scientific calculator
  Scientific calculator/Scientific calc preview.png
  Scientific calculator/index.html
  Scientific calculator/index.js
  Scientific calculator/readme.md
  Scientific calculator/style.css
Labels: GSSOC22, Level3

#383 first commit
  39.Reaction tester/README.md
  39.Reaction tester/jsrc.js
  39.Reaction tester/reaction tester.html
Labels: GSSOC22, Level3

#384 Added instagram Homepage UI created With HTML And CSS
  Instagram-HomePage/assets/add.PNG
  Instagram-HomePage/assets/comment.PNG
  Instagram-HomePage/assets/cover 1.png
  Instagram-HomePage/assets/cover 10.png
  Instagram-HomePage/assets/cover 11.png
  Instagram-HomePage/assets/cover 12.png
  Instagram-HomePage/assets/cover 13.png
  Instagram-HomePage/assets/cover 2.png
  Instagram-HomePage/assets/cover 3.png
  Instagram-HomePage/assets/cover 4.png
  Instagram-HomePage/assets/cover 5.png
  Instagram-HomePage/assets/cover 6.png
  Instagram-HomePage/assets/cover 7.png
  Instagram-HomePage/assets/cover 8.png
  Instagram-HomePage/assets/cover 9.png
  Instagram-HomePage/assets/explore.PNG
  Instagram-HomePage/assets/home.PNG
  Instagram-HomePage/assets/like.PNG
  Instagram-HomePage/assets/logo.PNG
  Instagram-HomePage/assets/messenger.PNG
  Instagram-HomePage/assets/option.PNG
  Instagram-HomePage/assets/profile-pic.png
  Instagram-HomePage/assets/save.PNG
  Instagram-HomePage/assets/send.PNG
  Instagram-HomePage/assets/smile.PNG
  Instagram-HomePage/index.html
  Instagram-HomePage/style.css
Labels: GSSOC22, Level3

#387 Parallex Web Design Added
  Parallex-Web-Design/Images/image1.jpg
  Parallex-Web-Design/Images/image2.jpg
  Parallex-Web-Design/Images/image3.jpg
  Parallex-Web-Design/ParallexEffect.css
  Parallex-Web-Design/ParallexEffect.html
  Parallex-Web-Design/demo.png
  Parallex-Web-Design/readme.md
  README.md
Labels: GSSOC22, Level3

#388 Added Technical Documentation Page on JavaScript
  Technical Documentation Page/README.md
  Technical Documentation Page/index.css
  Technical Documentation Page/index.html
Labels: GSSOC22, Level3

#393 added passenger counter
  passenger-counter-web/images/coffee-cup.png
  passenger-counter-web/images/michal-parzuchowski-dmH3NWhYTHQ-unsplash.jpg
  passenger-counter-web/index.html
  passenger-counter-web/index.js
  passenger-counter-web/readme.md
  passenger-counter-web/style.css
Labels: GSSOC22, Level3

#395 Sample Portfolio Page
  Sample Portfolio Page/README.md
  Sample Portfolio Page/index.html
  Sample Portfolio Page/style.css
Labels: GSSOC22, Level3
