Repository khushi-purwar/WebDev-ProjectKart, pull requests merged in 2022-04, with the labels that each got.

#396 Added Microsoft Teams Page Clone files
  Microsoft_Teams_Page_Clone/assets/css/bootstrap.css
  Microsoft_Teams_Page_Clone/assets/css/bootstrap.css.map
  Microsoft_Teams_Page_Clone/assets/css/style.css
  Microsoft_Teams_Page_Clone/assets/media/Capture.png
  Microsoft_Teams_Page_Clone/assets/media/Teams_Icon.jpg
  Microsoft_Teams_Page_Clone/assets/media/person.png
  Microsoft_Teams_Page_Clone/index.html
  Microsoft_Teams_Page_Clone/readme.md
  Microsoft_Teams_Page_Clone/scripts/bootstrap.bundle.js
  Microsoft_Teams_Page_Clone/scripts/bootstrap.bundle.js.map
Labels: GSSOC22, Level3

#399 Adding a new website template
  ShoeStore/README.md
  ShoeStore/public/favicon.ico
  ShoeStore/public/index.html
  ShoeStore/public/logo192.png
  ShoeStore/public/logo512.png
  ShoeStore/public/manifest.json
  ShoeStore/public/robots.txt
  ShoeStore/src/App.js
  ShoeStore/src/Components/Feature/FeatureElements.jsx
  ShoeStore/src/Components/Feature/index.jsx
  ShoeStore/src/Components/Footer/FooterElements.jsx
  ShoeStore/src/Components/Footer/index.jsx
  ShoeStore/src/Components/Hero/HeroElements.jsx
  ShoeStore/src/Components/Hero/index.jsx
  ShoeStore/src/Components/Navbar/NavbarElements.jsx
  ShoeStore/src/Components/Navbar/index.jsx
  ShoeStore/src/Components/Products/ProductsElements.jsx
  ShoeStore/src/Components/Products/data.jsx
  ShoeStore/src/Components/Products/index.jsx
  ShoeStore/src/Components/Sidebar/SidebarElements.jsx
  ShoeStore/src/Components/Sidebar/index.jsx
  ShoeStore/src/globalStyles.jsx
  ShoeStore/src/images/image1.jpg
  ShoeStore/src/images/image10.png
  ShoeStore/src/images/image11.jpg
  ShoeStore/src/images/image12.jpg
  ShoeStore/src/images/image2.jpg
  ShoeStore/src/images/image3.jpg
  ShoeStore/src/images/image4.jpg
  ShoeStore/src/images/image5.jpg
  ShoeStore/src/images/image6.jpg
  ShoeStore/src/images/image7.jpg
  ShoeStore/src/images/image8.jpg
  ShoeStore/src/index.js
Labels: GSSOC22, Level3

#409 Claymorphism Effect Added
  Claymorphism-Effect/index.html
  Claymorphism-Effect/preview.png
  Claymorphism-Effect/readme.md
  Claymorphism-Effect/style.css
  README.md
Labels: GSSOC22, Level3

#411 Added Instagram Login/Signup Page Clone
  Instagram Login cum Signup Page Clone/Assets/media/igicon.png
  Instagram Login cum Signup Page Clone/Assets/media/meta.png
  Instagram Login cum Signup Page Clone/README.md
  Instagram Login cum Signup Page Clone/index.css
  Instagram Login cum Signup Page Clone/index.html
Labels: GSSOC22, Level3

#414 Simple Landing page UI of an NFT website. (reference to issue #389)
  Landing page UI of an NFT website/UI.png
  Landing page UI of an NFT website/images/binance.svg
  Landing page UI of an NFT website/images/bitfinex.svg
  Landing page UI of an NFT website/images/discord.svg
  Landing page UI of an NFT website/images/kraken.svg
  Landing page UI of an NFT website/images/lazy.jpg
  Landing page UI of an NFT website/images/minimal.jpg
  Landing page UI of an NFT website/images/nft.jpg
  Landing page UI of an NFT website/images/weight.jpg
  Landing page UI of an NFT website/index.html
Labels: GSSOC22, Level3

#361 CV Screener added
  CV_Screener/README.md
  CV_Screener/app.js
  CV_Screener/bg.png
  CV_Screener/index.html
  CV_Screener/styles.css
  CV_Screener/table.png
Labels: GSSOC22, Level3

#445 Added Google Search Engine Clone
  Google-Search-Engine-Clone/.eslintcache
  Google-Search-Engine-Clone/.gitignore
  Google-Search-Engine-Clone/README.md
  Google-Search-Engine-Clone/package-lock.json
  Google-Search-Engine-Clone/package.json
  Google-Search-Engine-Clone/public/favicon.ico
  Google-Search-Engine-Clone/public/index.html
  Google-Search-Engine-Clone/public/manifest.json
  Google-Search-Engine-Clone/public/robots.txt
  Google-Search-Engine-Clone/src/App.css
  Google-Search-Engine-Clone/src/App.js
  Google-Search-Engine-Clone/src/Home.css
  Google-Search-Engine-Clone/src/Home.js
  Google-Search-Engine-Clone/src/Search.css
  Google-Search-Engine-Clone/src/Search.js
  Google-Search-Engine-Clone/src/SearchPage.css
  Google-Search-Engine-Clone/src/SearchPage.js
  Google-Search-Engine-Clone/src/StateProvider.js
  Google-Search-Engine-Clone/src/config.js
  Google-Search-Engine-Clone/src/index.css
  Google-Search-Engine-Clone/src/index.js
  Google-Search-Engine-Clone/src/reducer.js
  Google-Search-Engine-Clone/src/reportWebVitals.js
  Google-Search-Engine-Clone/src/response.js
  Google-Search-Engine-Clone/src/useGoogleSearch.js
Labels: GSSOC22, Level3

#436 Live user filter
  Live User Filter/README.md
  Live User Filter/index.html
  Live User Filter/script.js
  Live User Filter/style.css
Labels: GSSOC22, Level3

#429 Parallax web page
  Parallax webpage/README.md
  Parallax webpage/astro.png
  Parallax webpage/index.html
  Parallax webpage/m_1.png
  Parallax webpage/m_3.png
  Parallax webpage/paralax.js
Labels: GSSOC22, Level3

#428 GameMemory Card Game
  Memory Card/README.md
  Memory Card/css/style.css
  Memory Card/images/add-readme.png
  Memory Card/images/csss.jpg
  Memory Card/images/csss1.jpg
  Memory Card/images/img-1.png
  Memory Card/images/img-2.png
  Memory Card/images/img-3.png
  Memory Card/images/img-4.png
  Memory Card/images/img-5.png
  Memory Card/images/img-6.png
  Memory Card/images/img-7.png
  Memory Card/images/img-8.png
  Memory Card/images/question_mark_black_24dp.svg
  Memory Card/index.html
  Memory Card/js/app.js
Labels: GSSOC22, Level3

#426 Added Zipp-ER
  Zipp-ER/.gitignore
  Zipp-ER/README.md
  Zipp-ER/assets/css/style.css
  Zipp-ER/backend/app.js
  Zipp-ER/backend/package-lock.json
  Zipp-ER/backend/package.json
  Zipp-ER/index.html
  Zipp-ER/scripts/index.js
Labels: GSSOC22, Level3

#198 Add News Website
  News_Website/COVID19 red logo.png
  News_Website/Readme.md
  News_Website/app.css
  News_Website/app3.js
  News_Website/app3b.js
  News_Website/index.html
  index.html
Labels: GSSOC22, Level3

#441 Added Electricity Bill Calculator
  Electricity Bill Calculator/Readme.md
  Electricity Bill Calculator/index.html
  Electricity Bill Calculator/script/script.js
  Electricity Bill Calculator/snips/electricity_ss1.png
  Electricity Bill Calculator/snips/logic.png
  Electricity Bill Calculator/style/style.css
Labels: GSSOC22, Level3

#447 Added 2048 game
  2048 Game/.gitignore
  2048 Game/2048.gif
  2048 Game/README.md
  2048 Game/package-lock.json
  2048 Game/package.json
  2048 Game/public/2048.svg
  2048 Game/public/index.html
  2048 Game/public/manifest.json
  2048 Game/public/robots.txt
  2048 Game/src/Styles.js
  2048 Game/src/TwentyFourtyEight.css
  2048 Game/src/TwentyFourtyEight.js
  2048 Game/src/grid.svg
  2048 Game/src/index.css
  2048 Game/src/index.js
  2048 Game/src/package.json
  2048 Game/src/restart.svg
  2048 Game/src/serviceWorker.js
  2048 Game/src/undo.svg
Labels: GSSOC22, Level3

#470 Guess the word game
  Guess the Word/index.html
  Guess the Word/readme.md
  Guess the Word/scripts/app.js
  Guess the Word/scripts/hangman.js
  Guess the Word/scripts/request.js
  Guess the Word/styles/styles.css
Labels: GSSOC22, Level3

#459 Mobile Number Validator Added
  Mobile-Number-Validator/README.md
  Mobile-Number-Validator/script.js
  Mobile-Number-Validator/style.css
  Mobile-Number-Validator/validator.html
  README.md
Labels: GSSOC22, Level3

#468 Added expense Tracker
  Expense_Tracker/REAMDE.md
  Expense_Tracker/index.html
  Expense_Tracker/style.css
  Expense_Tracker/work.js
Labels: GSSOC22, Level3

#466 Magic 8 Ball Added
  Magic-8-Ball/README.md
  Magic-8-Ball/index.html
  Magic-8-Ball/script.js
  Magic-8-Ball/style.css
  README.md
Labels: GSSOC22, Level3

#463 Pomodoro Clock added
  Pomodoro-Clock/README.md
  Pomodoro-Clock/clock.html
  Pomodoro-Clock/script.js
  Pomodoro-Clock/style.css
  README.md
Labels: GSSOC22, Level3

#461 Roman Numeral Converter added
  README.md
  Roman-Numeral-Converter/README.md
  Roman-Numeral-Converter/converter.html
  Roman-Numeral-Converter/script.js
  Roman-Numeral-Converter/style.css
Labels: GSSOC22, Level3

#476 Breakout Game
  Breakout Game/assets/style.css
  Breakout Game/index.html
  Breakout Game/readme.md
  Breakout Game/script/index.js
Labels: GSSOC22, Level3

#478 Balloon popper added
  Balloon-Popper/README.md
  Balloon-Popper/app.js
  Balloon-Popper/index.html
  Balloon-Popper/style.css
Labels: GSSOC22, Level3

#489 Motivational quote generator, Resolving issue #474
  Motivational-Quote-Generator/index.html
  Motivational-Quote-Generator/readme.md
  Motivational-Quote-Generator/script.js
  Motivational-Quote-Generator/style1.css
  Motivational-Quote-Generator/style2.css
Labels: GSSOC22, Level3

#482 Added Typing Master Clone
  Typing Master Game Clone/index.html
  Typing Master Game Clone/js/paragraphs.js
  Typing Master Game Clone/js/script.js
  Typing Master Game Clone/particle.jpeg
  Typing Master Game Clone/style.css
Labels: GSSOC22, Level3

#481 Added Wordle Clone
  README.md
  Wordle Clone/Assets/css
  Wordle Clone/README.md
  Wordle Clone/index.html
  Wordle Clone/script/script.js
  Wordle Clone/script/wordlist.js
Labels: GSSOC22, Level3

#491 Speech Recognition Website
  Speech Recognition/index.html
  Speech Recognition/readme.md
  Speech Recognition/script.js
  Speech Recognition/style.css
Labels: GSSOC22, Level3

#493 Added JavaScript Timer
  JavaScript Timer/Readme.md
  JavaScript Timer/index.html
  JavaScript Timer/script/script.js
  JavaScript Timer/snips/snip1.png
  JavaScript Timer/snips/snip2.png
  JavaScript Timer/style/style.css
Labels: GSSOC22, Level3

#513 Pinterest extension
  Pinterest_extension/.vscode/settings.json
  Pinterest_extension/board.html
  Pinterest_extension/images/icon-128x128.png
  Pinterest_extension/images/icon-16x16.png
  Pinterest_extension/images/icon-32x32.png
  Pinterest_extension/images/icon-48x48.png
  Pinterest_extension/images/pinterest-mock/add.png
  Pinterest_extension/images/pinterest-mock/ellipse.png
  Pinterest_extension/images/pinterest-mock/send.png
  Pinterest_extension/images/pinterest-mock/up-arrow.png
  Pinterest_extension/images/pinterest-mock/upper-right-arrow.png
  Pinterest_extension/manifest.json
  Pinterest_extension/options.html
  Pinterest_extension/popup.html
  Pinterest_extension/readme.md
  Pinterest_extension/scripts/background.js
  Pinterest_extension/scripts/pinterest-mock/board.js
  Pinterest_extension/scripts/popup_script.js
  Pinterest_extension/styles/pinterest-mock/board.css
  Pinterest_extension/styles/pinterest-mock/modal_styles.css
  Pinterest_extension/styles/pinterest-mock/normalize.css
  Pinterest_extension/styles/pinterest-mock/pin_styles.css
  Pinterest_extension/styles/popup_styles.css
Labels: GSSOC22, Level3

#496 Brick breaker added
  Brick-breaker-game/README.md
  Brick-breaker-game/index.html
  Brick-breaker-game/script.js
  Brick-breaker-game/style.css
Labels: GSSOC22, Level3

#498 Added Google mail clone files
  Google_Mail_Clone/assets/css/bootstrap.css
  Google_Mail_Clone/assets/css/bootstrap.css.map
  Google_Mail_Clone/assets/css/style.css
  Google_Mail_Clone/assets/media/Capture.PNG
  Google_Mail_Clone/assets/media/allmail.png
  Google_Mail_Clone/assets/media/arrow_down.png
  Google_Mail_Clone/assets/media/avatar.png
  Google_Mail_Clone/assets/media/compose.png
  Google_Mail_Clone/assets/media/drafts.png
  Google_Mail_Clone/assets/media/gmail.ico
  Google_Mail_Clone/assets/media/inbox-red.png
  Google_Mail_Clone/assets/media/inbox.png
  Google_Mail_Clone/assets/media/joinmeet.png
  Google_Mail_Clone/assets/media/logo.png
  Google_Mail_Clone/assets/media/more.png
  Google_Mail_Clone/assets/media/newmeet.png
  Google_Mail_Clone/assets/media/promotions.png
  Google_Mail_Clone/assets/media/record-checkbox.png
  Google_Mail_Clone/assets/media/refresh.png
  Google_Mail_Clone/assets/media/sent.png
  Google_Mail_Clone/assets/media/social.png
  Google_Mail_Clone/assets/media/spam.png
  Google_Mail_Clone/assets/media/star.png
  Google_Mail_Clone/assets/media/toolbar_checkbox.png
  Google_Mail_Clone/assets/media/trash.png
  Google_Mail_Clone/index.html
  Google_Mail_Clone/readme.md
  Google_Mail_Clone/scripts/bootstrap.bundle.js
  Google_Mail_Clone/scripts/bootstrap.bundle.js.map
Labels: GSSOC22, Level3

#502 Snake Game
  35.Snake_Game/README.md
  35.Snake_Game/Snake-Game.png
  35.Snake_Game/images/apple1.png
  35.Snake_Game/images/mango.png
  35.Snake_Game/images/pear.png
  35.Snake_Game/images/wp2409705.jpg
  35.Snake_Game/index.html
  35.Snake_Game/script.js
  35.Snake_Game/style.css
Labels: GSSOC22, Level3

#515 Currency Converter Project
  Currency Converter/README.md
  Currency Converter/exchange sign.png
  Currency Converter/index.html
  Currency Converter/script.js
  Currency Converter/style.css
Labels: GSSOC22, Level3

#512 Burger Eye
  Burger Eye/README.md
  Burger Eye/burger.png
  Burger Eye/favicon.png
  Burger Eye/index.html
  Burger Eye/index.js
  Burger Eye/style.css
Labels: GSSOC22, Level3

#521 Added racing game with all its files
  Racing_Game/car1.jpeg
  Racing_Game/car2.jpeg
  Racing_Game/index.html
  Racing_Game/newcar1.png
  Racing_Game/newcar2.png
  Racing_Game/newtree.png
  Racing_Game/readme.md
  Racing_Game/script.js
  Racing_Game/style.css
  Racing_Game/tree.jpeg
  images/racing game.jpg
  index.html
Labels: GSSOC22, Level3

#525 Added Animated Mouse Cursor
  Animated Mouse Cursor/Readme.md
  Animated Mouse Cursor/assets/cursor.png
  Animated Mouse Cursor/index.html
  Animated Mouse Cursor/scripts/script.js
  Animated Mouse Cursor/snips/snip1.png
  Animated Mouse Cursor/style/style.css
Labels: GSSOC22, Level3

#509 Expanding cards added
  Expanding-Cards/README.md
  Expanding-Cards/index.html
  Expanding-Cards/script.js
  Expanding-Cards/style.css
Labels: GSSOC22, Level3

#511 Insect Catch Game added
  Insect-Catch-Game/README.md
  Insect-Catch-Game/index.html
  Insect-Catch-Game/script.js
  Insect-Catch-Game/style.css
Labels: GSSOC22, Level3

#499 Hangman Puzzle Added
  Hangman-Puzzle/README.md
  Hangman-Puzzle/index.html
  Hangman-Puzzle/scripts/app.js
  Hangman-Puzzle/scripts/hangman.js
  Hangman-Puzzle/scripts/request.js
  Hangman-Puzzle/styles/style.css
Labels: GSSOC22, Level3

#520 Casino Slot Machine Game
  Casino Slot Machine Game/index.html
  Casino Slot Machine Game/readme.md
  Casino Slot Machine Game/script.js
  Casino Slot Machine Game/style.css
Labels: GSSOC22, Level3

#522 Added Sorting Visualizer
  Sorting Visulaizer/README.md
  Sorting Visulaizer/package-lock.json
  Sorting Visulaizer/package.json
  Sorting Visulaizer/public/favicon.ico
  Sorting Visulaizer/public/index.html
  Sorting Visulaizer/public/logo192.png
  Sorting Visulaizer/public/logo512.png
  Sorting Visulaizer/public/manifest.json
  Sorting Visulaizer/public/robots.txt
  Sorting Visulaizer/src/App.css
  Sorting Visulaizer/src/App.js
  Sorting Visulaizer/src/algorithms/BS.js
  Sorting Visulaizer/src/algorithms/helpers.js
  Sorting Visulaizer/src/components/Bar.css
  Sorting Visulaizer/src/components/Bar.js
  Sorting Visulaizer/src/index.css
  Sorting Visulaizer/src/index.js
  Sorting Visulaizer/src/reportWebVitals.js
Labels: GSSOC22, Level3

#533 Snake game using speech recognition in javascript
  SnakeGame_SpeechRecognition/index.html
  SnakeGame_SpeechRecognition/main.js
  SnakeGame_SpeechRecognition/readme.md
  SnakeGame_SpeechRecognition/speechCommand.js
  SnakeGame_SpeechRecognition/style.css
Labels: GSSOC22, Level3

#536 Random color Generator based on HexaDecimal System
  Color Generator/design.css
  Color Generator/index.html
  Color Generator/readme.md
  Color Generator/script.js
Labels: GSSOC22, Level3

#545 Text-To-Speech Convertor Added
  Text-To-Speech-Convertor/README.md
  Text-To-Speech-Convertor/index.html
  Text-To-Speech-Convertor/script.js
  Text-To-Speech-Convertor/style.css
Labels: GSSOC22, Level3

#538 Added Speed Reader App
  Speed Reader App/Readme.md
  Speed Reader App/index.html
  Speed Reader App/script.js
  Speed Reader App/style.css
Labels: GSSOC22, Level3

#530 Added Keeper ReactAPP
  Keeper/Readme.md
  Keeper/package.json
  Keeper/public/index.html
  Keeper/public/styles.css
  Keeper/src/components/App.jsx
  Keeper/src/components/CreateArea.jsx
  Keeper/src/components/Footer.jsx
  Keeper/src/components/Header.jsx
  Keeper/src/components/Note.jsx
  Keeper/src/index.js
Labels: GSSOC22, Level3

#529 Added Hacker News ReactApp
  Hacker News/Readme.md
  Hacker News/package-lock.json
  Hacker News/package.json
  Hacker News/public/favicon.ico
  Hacker News/public/index.html
  Hacker News/public/logo192.png
  Hacker News/public/logo512.png
  Hacker News/public/manifest.json
  Hacker News/public/robots.txt
  Hacker News/src/App.js
  Hacker News/src/Buttons.js
  Hacker News/src/SearchForm.js
  Hacker News/src/Stories.js
  Hacker News/src/actions.js
  Hacker News/src/context.js
  Hacker News/src/index.css
  Hacker News/src/index.js
  Hacker News/src/reducer.js
Labels: GSSOC22, Level3

#544 added login page
  README.md
  innovative-login-form/assests/ani1-removebg-preview.png
  innovative-login-form/assests/ani2-removebg-preview.png
  innovative-login-form/assests/i2.jpg
  innovative-login-form/assests/i3.jpg
  innovative-login-form/assests/images-removebg-preview.png
  innovative-login-form/public/index.html
  innovative-login-form/public/mystyle.css
Labels: GSSOC22, Level3

#590 Added Neumophormic Login Form
  .vscode/settings.json
  Neumophormic Login Form/README.md
  Neumophormic Login Form/index.html
  Neumophormic Login Form/style.css
Labels: GSSOC22, Level3

#586 Added Starbucks Clone
  Starbucks-Clone/Images/facebook.png
  Starbucks-Clone/Images/img1.png
  Starbucks-Clone/Images/img2.png
  Starbucks-Clone/Images/img3.png
  Starbucks-Clone/Images/instagram.png
  Starbucks-Clone/Images/logo.png
  Starbucks-Clone/Images/thumb1.png
  Starbucks-Clone/Images/thumb2.png
  Starbucks-Clone/Images/thumb3.png
  Starbucks-Clone/Images/twitter.png
  Starbucks-Clone/Readme.md
  Starbucks-Clone/index.css
  Starbucks-Clone/index.html
  Starbucks-Clone/main.js
Labels: GSSOC22, Level3

#550 Split Landing Page Added
  Split-Landing-Page/README.md
  Split-Landing-Page/index.html
  Split-Landing-Page/ps.jpg
  Split-Landing-Page/script.js
  Split-Landing-Page/style.css
  Split-Landing-Page/xbox.jpg
Labels: GSSOC22, Level3

#575 Added Patatap Clone
  Patatap  Clone/assets/Circles.gif
  Patatap  Clone/assets/sounds/bubbles.mp3
  Patatap  Clone/assets/sounds/clay.mp3
  Patatap  Clone/assets/sounds/confetti.mp3
  Patatap  Clone/assets/sounds/corona.mp3
  Patatap  Clone/assets/sounds/dotted-spiral.mp3
  Patatap  Clone/assets/sounds/flash-1.mp3
  Patatap  Clone/assets/sounds/flash-2.mp3
  Patatap  Clone/assets/sounds/flash-3.mp3
  Patatap  Clone/assets/sounds/glimmer.mp3
  Patatap  Clone/assets/sounds/moon.mp3
  Patatap  Clone/assets/sounds/pinwheel.mp3
  Patatap  Clone/assets/sounds/piston-1.mp3
  Patatap  Clone/assets/sounds/piston-2.mp3
  Patatap  Clone/assets/sounds/piston-3.mp3
  Patatap  Clone/assets/sounds/prism-1.mp3
  Patatap  Clone/assets/sounds/prism-2.mp3
  Patatap  Clone/assets/sounds/prism-3.mp3
  Patatap  Clone/assets/sounds/splits.mp3
  Patatap  Clone/assets/sounds/squiggle.mp3
  Patatap  Clone/assets/sounds/strike.mp3
  Patatap  Clone/assets/sounds/suspension.mp3
  Patatap  Clone/assets/sounds/timer.mp3
  Patatap  Clone/assets/sounds/ufo.mp3
  Patatap  Clone/assets/sounds/veil.mp3
  Patatap  Clone/assets/sounds/wipe.mp3
  Patatap  Clone/assets/sounds/zig-zag.mp3
  Patatap  Clone/circles.css
  Patatap  Clone/circles.html
  Patatap  Clone/paper-full.js
  Patatap  Clone/readme.md
Labels: GSSOC22, Level3

#556 Added Word Shuffle on Hover Project
  Word Shuffle on Hover/Readme.md
  Word Shuffle on Hover/index.html
  Word Shuffle on Hover/script/script.js
  Word Shuffle on Hover/snips/snip.png
  Word Shuffle on Hover/style/style.css
Labels: GSSOC22, Level3

#574 Added Telegram WebApp Clone files
  Telegram_Web_Clone/assets/css/style.css
  Telegram_Web_Clone/assets/media/Capture.PNG
  Telegram_Web_Clone/assets/media/avatar.png
  Telegram_Web_Clone/assets/media/background.png
  Telegram_Web_Clone/assets/media/icon.ico
  Telegram_Web_Clone/index.html
  Telegram_Web_Clone/readme.md
Labels: GSSOC22, Level3

#573 Fake-Address Generator
  Fake-Address Generator/ReadMe.MD
  Fake-Address Generator/bgroad.jpg
  Fake-Address Generator/index.html
  Fake-Address Generator/style.css
Labels: GSSOC22, Level3

#570 Recipe App added
  Recipe App/README.md
  Recipe App/package.json
  Recipe App/public/favicon.ico
  Recipe App/public/feed.js
  Recipe App/public/index.html
  Recipe App/public/logo.png
  Recipe App/public/logo192.png
  Recipe App/public/logo512.png
  Recipe App/public/manifest.json
  Recipe App/public/robots.txt
  Recipe App/public/worker.js
  Recipe App/src/App.css
  Recipe App/src/App.js
  Recipe App/src/App.test.js
  Recipe App/src/components/AboutUs.js
  Recipe App/src/components/Navigation.js
  Recipe App/src/components/Profile.js
  Recipe App/src/components/Recipe.js
  Recipe App/src/components/logo.jpg
  Recipe App/src/components/profile.module.css
  Recipe App/src/components/recipe.module.css
  Recipe App/src/components/tasty.png
  Recipe App/src/index.css
  Recipe App/src/index.js
  Recipe App/src/logo.svg
  Recipe App/src/reportWebVitals.js
  Recipe App/src/service-worker.js
  Recipe App/src/serviceWorkerRegistration.js
  Recipe App/src/setupTests.js
Labels: GSSOC22, Level3

#559 Flappy Bird Game
  Flappy Bird Game/assets/flappy-bird.png
  Flappy Bird Game/assets/style.css
  Flappy Bird Game/index.html
  Flappy Bird Game/readme.md
  Flappy Bird Game/script/index.js
Labels: GSSOC22, Level3

#561 Hunt the mole game, Resolving issue #490
  Hunt-The-Mole-Game/dirt.png
  Hunt-The-Mole-Game/index.html
  Hunt-The-Mole-Game/mole.jpg
  Hunt-The-Mole-Game/mole.png
  Hunt-The-Mole-Game/readme.md
  Hunt-The-Mole-Game/script.js
  Hunt-The-Mole-Game/style.css
Labels: GSSOC22, Level3

#553 Form Wave Project Added
  Form Wave/README.md
  Form Wave/index.html
  Form Wave/script.js
  Form Wave/style.css
Labels: GSSOC22, Level3

#552 Blurry Landing Project added
  Blurry-Loading-Project/README.md
  Blurry-Loading-Project/index.html
  Blurry-Loading-Project/script.js
  Blurry-Loading-Project/style.css
Labels: GSSOC22, Level3

#569 Dad Jokes Project added
  Colorful_Rain_Effect/.vscode/settings.json
  Dad-Jokes/README.md
  Dad-Jokes/index.html
  Dad-Jokes/script.js
  Dad-Jokes/style.css
Labels: GSSOC22, Level3

#551 Rotated Animation Navigation Added
  Rotating-Animation-Navigation/README.md
  Rotating-Animation-Navigation/index.html
  Rotating-Animation-Navigation/script.js
  Rotating-Animation-Navigation/style.css
Labels: GSSOC22, Level3

#583 Random-password generator program added
  Random-password-generator/README.md
  Random-password-generator/index.css
  Random-password-generator/index.html
  Random-password-generator/index.js
Labels: GSSOC22, Level3

#629 Rock Paper Scissors Game
  Game of Rock Paper Scissors/README.md
  Game of Rock Paper Scissors/index.html
  Game of Rock Paper Scissors/script.js
  Game of Rock Paper Scissors/styles.css
Labels: GSSOC22, Level3

#577 Added guess the number game
  Guess The Number Game/README.md
  Guess The Number Game/index.html
  Guess The Number Game/pexels-pixabay-531880.jpg
  Guess The Number Game/script.js
  Guess The Number Game/style.css
Labels: GSSOC22, Level3

#581 Added ci calculator
  Compound Interest Calculator/index.html
  Compound Interest Calculator/readme.md
  Compound Interest Calculator/script.js
  Compound Interest Calculator/style.css
  Compound Interest Calculator/sunny.jpg
Labels: GSSOC22, Level3

#567 Scroll Animation Page added
  Scroll-Animation-Page/README.md
  Scroll-Animation-Page/index.html
  Scroll-Animation-Page/script.js
  Scroll-Animation-Page/style.css
Labels: GSSOC22, Level3

#597 Added Typing Effect Project
  Typing Effect/Readme.md
  Typing Effect/assets/snip1.png
  Typing Effect/index.html
  Typing Effect/script/script.js
  Typing Effect/style/style.css
Labels: GSSOC22, Level3

#608 Added wordle clone
  Wordle_Clone/README.md
  Wordle_Clone/index.html
  Wordle_Clone/script.js
  Wordle_Clone/style.css
Labels: GSSOC22, Level3

#663 SVG webpage
  SVG animation effect/README.md
  SVG animation effect/index.html
  SVG animation effect/styles.css
Labels: GSSOC22, Level3

#611 Added Chess Board Game Design
  Chess Board Game Design/back.jpeg
  Chess Board Game Design/index.html
  Chess Board Game Design/readme.md
  Chess Board Game Design/style.css
Labels: GSSOC22, Level3

#613 Facebook Login Page
  Facebook Login Page/index.html
  Facebook Login Page/readme.md
  Facebook Login Page/style.css
Labels: GSSOC22, Level3

#614 Added Lorem Ipsum React App
  Lorem Ipsum/Readme.md
  Lorem Ipsum/package-lock.json
  Lorem Ipsum/package.json
  Lorem Ipsum/public/favicon.ico
  Lorem Ipsum/public/index.html
  Lorem Ipsum/public/logo192.png
  Lorem Ipsum/public/logo512.png
  Lorem Ipsum/public/manifest.json
  Lorem Ipsum/public/robots.txt
  Lorem Ipsum/src/App.js
  Lorem Ipsum/src/data.js
  Lorem Ipsum/src/index.css
  Lorem Ipsum/src/index.js
Labels: GSSOC22, Level3

#615 Added Cocktail App
  Cocktail/README.md
  Cocktail/package-lock.json
  Cocktail/package.json
  Cocktail/public/_redirects
  Cocktail/public/favicon.ico
  Cocktail/public/index.html
  Cocktail/public/logo192.png
  Cocktail/public/logo512.png
  Cocktail/public/manifest.json
  Cocktail/public/robots.txt
  Cocktail/src/App.js
  Cocktail/src/components/Cocktail.js
  Cocktail/src/components/CocktailList.js
  Cocktail/src/components/Loading.js
  Cocktail/src/components/Navbar.js
  Cocktail/src/components/SearchForm.js
  Cocktail/src/context.js
  Cocktail/src/index.css
  Cocktail/src/index.js
  Cocktail/src/logo.svg
  Cocktail/src/pages/About.js
  Cocktail/src/pages/Error.js
  Cocktail/src/pages/Home.js
  Cocktail/src/pages/SingleCocktail.js
Labels: GSSOC22, Level3

#622 Incrementing Counter Added
  Incrementing Counter/README.md
  Incrementing Counter/index.html
  Incrementing Counter/script.js
  Incrementing Counter/style.css
Labels: GSSOC22, Level3

#626 Add Run Mario Run Game with Sound Effects and Score Board
  Run Mario Run/README.md
  Run Mario Run/assets/audio/gameover.mp3
  Run Mario Run/assets/audio/music.mp3
  Run Mario Run/assets/images/Enemy.png
  Run Mario Run/assets/images/Mario.png
  Run Mario Run/assets/images/bg.png
  Run Mario Run/index.html
  Run Mario Run/scripts/script.js
  Run Mario Run/styles/style.css
Labels: GSSOC22, Level3

#635 particles js animation
  Particle js animation/README.md
  Particle js animation/app.js
  Particle js animation/index.html
  Particle js animation/particles.js
Labels: GSSOC22, Level3

#656 Added QR Code Scanner
  QR Code Scanner/Assets/css/index.css
  QR Code Scanner/README.md
  QR Code Scanner/index.html
  QR Code Scanner/scripts/index.js
Labels: GSSOC22, Level3

#662 Added Flashlight Pointer Game
  Flashlight Pointer Game/Readme.md
  Flashlight Pointer Game/assets/rabbit.png
  Flashlight Pointer Game/index.html
  Flashlight Pointer Game/script/script.js
  Flashlight Pointer Game/snips/snip1.png
  Flashlight Pointer Game/style/style.css
Labels: GSSOC22, Level3

#645 Added Heroku Dashboard Clone Files
  Heroku_Clone/assets/css/style.css
  Heroku_Clone/assets/media/Capture.PNG
  Heroku_Clone/assets/media/avatar.webp
  Heroku_Clone/assets/media/icon.ico
  Heroku_Clone/assets/media/mark.png
  Heroku_Clone/assets/media/python.png
  Heroku_Clone/assets/media/star.png
  Heroku_Clone/index.html
  Heroku_Clone/readme.md
Labels: GSSOC22, Level3

#661 Microsoft Clone added
  Microsoft Clone/README.md
  Microsoft Clone/app.js
  Microsoft Clone/index.html
  Microsoft Clone/style.css
Labels: GSSOC22, Level3

#689 QR CODE GENERATOR
  QR CODE/index.html
  QR CODE/readme.md
  QR CODE/script.js
  QR CODE/style.css
Labels: GSSOC22, Level3

#714 Event Calender📆
  Event Calender/images/time.png
  Event Calender/index.html
  Event Calender/readme.md
  Event Calender/style.css
Labels: GSSOC22, Level3

#677 Added Falling Snowflakes Effect
  Falling SnowFlakes Effect/Readme.md
  Falling SnowFlakes Effect/index.html
  Falling SnowFlakes Effect/script/script.js
  Falling SnowFlakes Effect/snips/snip1.png
  Falling SnowFlakes Effect/style/style.css
Labels: GSSOC22, Level3

#681 Added StackShare Clone Files
  StackShare_Clone/assets/css/style.css
  StackShare_Clone/assets/media/Capture.PNG
  StackShare_Clone/assets/media/avatar.png
  StackShare_Clone/assets/media/icon.svg
  StackShare_Clone/assets/media/tech/csv.png
  StackShare_Clone/assets/media/tech/git.png
  StackShare_Clone/assets/media/tech/github.jpg
  StackShare_Clone/assets/media/tech/javascript.jpeg
  StackShare_Clone/assets/media/tech/nodejs.png
  StackShare_Clone/assets/media/tech/postgresql.png
  StackShare_Clone/assets/media/tech/python.png
  StackShare_Clone/assets/media/tech/react.png
  StackShare_Clone/index.html
  StackShare_Clone/readme.md
Labels: GSSOC22, Level3

#696 CSS Bicycle
  CSS Bicycle/README.md
  CSS Bicycle/index.html
  CSS Bicycle/style.css
Labels: GSSOC22, Level3

#707 Added Math Sprint Game
  Math Sprint Game/README.md
  Math Sprint Game/index.html
  Math Sprint Game/main.js
  Math Sprint Game/shuffle.js
  Math Sprint Game/style.css
Labels: GSSOC22, Level3

#675 QUIZ WEBSITE
  Quiz Website/README.md
  Quiz Website/finalPage.css
  Quiz Website/finalPage.html
  Quiz Website/index.html
  Quiz Website/quiz.css
  Quiz Website/quiz.html
  Quiz Website/quiz.js
  Quiz Website/score.css
  Quiz Website/score.html
  Quiz Website/score.js
  Quiz Website/style.css
  Quiz Website/work.js
Labels: GSSOC22, Level3

#625 Random Choice Picker added
  Random Choice Picker/README.md
  Random Choice Picker/index.html
  Random Choice Picker/script.js
  Random Choice Picker/style.css
Labels: GSSOC22, Level3

#624 Event Key Codes added
  Event KeyCodes/README.md
  Event KeyCodes/index.html
  Event KeyCodes/script.js
  Event KeyCodes/style.css
Labels: GSSOC22, Level3

#640 Added Video Player
  Video Player/README.md
  Video Player/index.html
  Video Player/script.js
  Video Player/style.css
Labels: GSSOC22, Level3

#690 Edited the readme file
  README.md
Labels: Level1, GSSOC22

#644 HTML5 Canvas Animation added
  HTML5 Canvas Animation/README.md
  HTML5 Canvas Animation/index.html
  HTML5 Canvas Animation/index.js
  HTML5 Canvas Animation/style.css
Labels: GSSOC22, Level3

#794 Dark-Light mode toggle
  Toggle Dark - Light Mode/README.md
  Toggle Dark - Light Mode/index.html
  Toggle Dark - Light Mode/style.css
Labels: Level2, GSSoC22, ready-to-merge

#796 Added Joke teller
  Joke teller/README.md
  Joke teller/index.html
  Joke teller/main.js
  Joke teller/style.css
  Joke teller/style.less
Labels: Level2, GSSoC22, ready-to-merge

#792 Amazon UI Clone
  Amazon UI/img/Appliances.jpg
  Amazon UI/img/Grocery.jpg
  Amazon UI/img/Laptops.jpg
  Amazon UI/img/Smartphones.jpg
  Amazon UI/img/cartBlack.png
  Amazon UI/img/cartWhite.png
  Amazon UI/img/logoBlack.png
  Amazon UI/img/logoWhite.png
  Amazon UI/img/profileBlack.png
  Amazon UI/img/profileWhite.png
  Amazon UI/img/search.png
  Amazon UI/index.html
  Amazon UI/readme.md
  Amazon UI/responsive.css
  Amazon UI/style.css
Labels: GSSoC22, Level3, ready-to-merge

#773 Added Click Counter Application
  Click Counter Application/Readme.md
  Click Counter Application/index.html
  Click Counter Application/script/script.js
  Click Counter Application/snips/snip1.png
  Click Counter Application/style/style.css
Labels: Level1, GSSoC22, ready-to-merge

#697 Improving README.md file
  README.md
Labels: Level1, GSSoC22, ready-to-merge

#659 Added my portfolio
  Nikhil Mahana's Portfolio/Readme.md
  Nikhil Mahana's Portfolio/images/My-Banner.png
  Nikhil Mahana's Portfolio/images/icon-1.jpg
  Nikhil Mahana's Portfolio/images/icon.jpg
  Nikhil Mahana's Portfolio/images/profile-1.png
  Nikhil Mahana's Portfolio/index.html
  Nikhil Mahana's Portfolio/script.js
  Nikhil Mahana's Portfolio/style.css
Labels: Level1, GSSoC22, ready-to-merge

#735 Added Speed Typer
  Speed Typer/Readme.md
  Speed Typer/index.html
  Speed Typer/script.js
  Speed Typer/style.css
Labels: Level2, GSSoC22, ready-to-merge

#766 Added Form Validator Application
  Form Validator/Readme.md
  Form Validator/index.html
  Form Validator/script.js
  Form Validator/style.css
Labels: Level1, GSSoC22, ready-to-merge

#738 Added New Year countdown project
  New-year-countdown/index.html
  New-year-countdown/script.js
  New-year-countdown/spinner (1).gif
  New-year-countdown/styles.css
Labels: Level1, GSSoC22, ready-to-merge

#745 Added Quora Clone
  QUORA-CLONE/README.md
  QUORA-CLONE/assets/Images/32048.webp
  QUORA-CLONE/assets/Images/Background.png
  QUORA-CLONE/assets/Images/image10.webp
  QUORA-CLONE/assets/Images/image11.jpeg
  QUORA-CLONE/assets/Images/image12.jpg
  QUORA-CLONE/assets/Images/image13.jpg
  QUORA-CLONE/assets/Images/image14.webp
  QUORA-CLONE/assets/Images/image15.webp
  QUORA-CLONE/assets/Images/image2.jpg
  QUORA-CLONE/assets/Images/image3.avif
  QUORA-CLONE/assets/Images/image4.jpeg
  QUORA-CLONE/assets/Images/image5.webp
  QUORA-CLONE/assets/Images/image6.webp
  QUORA-CLONE/assets/Images/image7.webp
  QUORA-CLONE/assets/Images/image8.webp
  QUORA-CLONE/assets/Images/image9.jpg
  QUORA-CLONE/assets/Images/kisspng-area-text-symbol-brand-computer-wallpaper-quora-5ab0b982e2b621.3292421215215312669286.jpg
  QUORA-CLONE/assets/css/all.css
  QUORA-CLONE/assets/css/all.min.css
  QUORA-CLONE/assets/css/brands.css
  QUORA-CLONE/assets/css/brands.min.css
  QUORA-CLONE/assets/css/fontawesome.css
  QUORA-CLONE/assets/css/fontawesome.min.css
  QUORA-CLONE/assets/css/regular.css
  QUORA-CLONE/assets/css/regular.min.css
  QUORA-CLONE/assets/css/solid.css
  QUORA-CLONE/assets/css/solid.min.css
  QUORA-CLONE/assets/css/svg-with-js.css
  QUORA-CLONE/assets/css/svg-with-js.min.css
  QUORA-CLONE/assets/css/v4-font-face.css
  QUORA-CLONE/assets/css/v4-font-face.min.css
  QUORA-CLONE/assets/css/v4-shims.css
  QUORA-CLONE/assets/css/v4-shims.min.css
  QUORA-CLONE/assets/css/v5-font-face.css
  QUORA-CLONE/assets/css/v5-font-face.min.css
  QUORA-CLONE/assets/webfonts/fa-brands-400.ttf
  QUORA-CLONE/assets/webfonts/fa-brands-400.woff2
  QUORA-CLONE/assets/webfonts/fa-regular-400.ttf
  QUORA-CLONE/assets/webfonts/fa-regular-400.woff2
  QUORA-CLONE/assets/webfonts/fa-solid-900.ttf
  QUORA-CLONE/assets/webfonts/fa-solid-900.woff2
  QUORA-CLONE/assets/webfonts/fa-v4compatibility.ttf
  QUORA-CLONE/assets/webfonts/fa-v4compatibility.woff2
  QUORA-CLONE/index.html
  QUORA-CLONE/style.css
Labels: Level2, GSSoC22, ready-to-merge

#761 React App (API)
  React App(API)/package-lock.json
  React App(API)/package.json
  React App(API)/public/bg.jpg
  React App(API)/public/favicon.ico
  React App(API)/public/index.html
  React App(API)/public/logo192.png
  React App(API)/public/manifest.json
  React App(API)/readme.md
  React App(API)/src/MyComponents/Card.js
  React App(API)/src/MyComponents/CardList.js
  React App(API)/src/MyComponents/Navigation/Navbar.css
  React App(API)/src/MyComponents/Navigation/Navigation.js
  React App(API)/src/MyComponents/Scroll.js
  React App(API)/src/container/App.js
  React App(API)/src/container/loader.js
  React App(API)/src/container/styles.css
  React App(API)/src/index.css
  React App(API)/src/index.js
  React App(API)/src/logo.svg
  React App(API)/src/reportWebVitals.js
  React App(API)/src/setupTests.js
Labels: GSSoC22, Level3, ready-to-merge

#750 LUDO DICE
  LUDO DICE/assets/1.png
  LUDO DICE/assets/2.png
  LUDO DICE/assets/3.png
  LUDO DICE/assets/4.png
  LUDO DICE/assets/5.png
  LUDO DICE/assets/6.png
  LUDO DICE/assets/dice-roll.gif
  LUDO DICE/assets/dice.png
  LUDO DICE/font/sans.ttf
  LUDO DICE/index.html
  LUDO DICE/readme.md
  LUDO DICE/script.js
  LUDO DICE/style.css
Labels: Level1, GSSoC22, ready-to-merge

#762 Added Google Drive Clone Files
  GoogleDrive_Clone/assets/css/style.css
  GoogleDrive_Clone/assets/media/Capture.PNG
  GoogleDrive_Clone/assets/media/avatar.png
  GoogleDrive_Clone/assets/media/icon.png
  GoogleDrive_Clone/assets/media/logo.png
  GoogleDrive_Clone/index.html
  GoogleDrive_Clone/readme.md
Labels: Level1, GSSoC22, ready-to-merge

#749 text speed controller
  Text Speed Control/assets/speed.png
  Text Speed Control/font/sans.ttf
  Text Speed Control/index.html
  Text Speed Control/readme.md
  Text Speed Control/script.js
  Text Speed Control/style.css
Labels: Level1, GSSoC22, ready-to-merge

#759 ON CLICK EMOJI CHANGER, solving issue #758
  On click Emoji Switcher/assets/cool.png
  On click Emoji Switcher/index.html
  On click Emoji Switcher/readme.md
  On click Emoji Switcher/script.js
  On click Emoji Switcher/style.css
Labels: Level1, GSSoC22, ready-to-merge

#744 Added Flappy Bird Game using Javascript
  Flappy Bird Game Using Javascript/Readme.md
  Flappy Bird Game Using Javascript/assets/img.png
  Flappy Bird Game Using Javascript/assets/point.mp3
  Flappy Bird Game Using Javascript/index.html
  Flappy Bird Game Using Javascript/script/script.js
  Flappy Bird Game Using Javascript/snips/snip1.png
  Flappy Bird Game Using Javascript/style/style.css
Labels: GSSoC22, Level3

#768 Added Cloud Deployment Landing Page
  Loruki Landing Page/Readme.md
  Loruki Landing Page/index.html
  Loruki Landing Page/style.css
  Loruki Landing Page/utilities.css
Labels: Level2, GSSoC22, ready-to-merge

#779 Added Theme Builder
  themeBuilder/README.md
  themeBuilder/package.json
  themeBuilder/public/favicon.ico
  themeBuilder/public/index.html
  themeBuilder/public/logo192.png
  themeBuilder/public/logo512.png
  themeBuilder/public/manifest.json
  themeBuilder/public/robots.txt
  themeBuilder/src/App.js
  themeBuilder/src/CreateThemeContent.js
  themeBuilder/src/Dialog.js
  themeBuilder/src/ThemeSelector.js
  themeBuilder/src/index.js
  themeBuilder/src/logo.svg
  themeBuilder/src/serviceWorker.js
  themeBuilder/src/setupTests.js
  themeBuilder/src/theme/GlobalStyles.js
  themeBuilder/src/theme/schema.json
  themeBuilder/src/theme/useTheme.js
  themeBuilder/src/utils/storage.js
  themeBuilder/static/Demo_1.gif
  themeBuilder/static/Demo_2.gif
  themeBuilder/static/themes-default.png
  themeBuilder/yarn.lock
Labels: Level2, GSSoC22, ready-to-merge

#693 Hulu UI Clone
  Hulu UI Clone/css/style.css
  Hulu UI Clone/img/close.svg
  Hulu UI Clone/img/cover-1.jpg
  Hulu UI Clone/img/cover-2.jpg
  Hulu UI Clone/img/cover-3.jpg
  Hulu UI Clone/img/cover-4.jpg
  Hulu UI Clone/img/facebook.svg
  Hulu UI Clone/img/favicon.ico.png
  Hulu UI Clone/img/header.jpg
  Hulu UI Clone/img/instagram.svg
  Hulu UI Clone/img/live-sports-logo-1.png
  Hulu UI Clone/img/live-sports-logo-2.png
  Hulu UI Clone/img/live-sports-logo-3.svg
  Hulu UI Clone/img/live-sports-logo-4.png
  Hulu UI Clone/img/live-sports-small.jpg
  Hulu UI Clone/img/live-sports.jpg
  Hulu UI Clone/img/logo.png
  Hulu UI Clone/img/logos.png
  Hulu UI Clone/img/network-logo-bg.png
  Hulu UI Clone/img/screen.png
  Hulu UI Clone/img/twitter.svg
  Hulu UI Clone/img/youtube.svg
  Hulu UI Clone/index.html
  Hulu UI Clone/js/main.js
  Hulu UI Clone/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#824 Transpose matrix calculator
  Matrix Transpose Calculator/index.html
  Matrix Transpose Calculator/readme.md
  Matrix Transpose Calculator/script.js
  Matrix Transpose Calculator/style.css
Labels: Level1, GSSoC22, ready-to-merge

#820 adding captcha generator
  Captcha Generator/assets/bg6.png
  Captcha Generator/assets/favicon.ico
  Captcha Generator/index.html
  Captcha Generator/readme.md
  Captcha Generator/script.js
  Captcha Generator/style.css
Labels: Level2, GSSoC22, ready-to-merge

#819 Number System Converter
  Number System Converter/index.html
  Number System Converter/readme.md
  Number System Converter/script.js
  Number System Converter/style.css
Labels: GSSoC22, Level3, ready-to-merge

#816 Bill Splitter
  Bill Splitter/edit.css
  Bill Splitter/index.html
  Bill Splitter/work.js
Labels: Level2, GSSoC22, ready-to-merge

#811 Tesla Homepage Clone
  Tesla HomePage Clone/Accessories.jpg
  Tesla HomePage Clone/READme.md
  Tesla HomePage Clone/Solar-Roof.jpg
  Tesla HomePage Clone/SolarPanels.jpg
  Tesla HomePage Clone/close-icon.png
  Tesla HomePage Clone/index.html
  Tesla HomePage Clone/model-3.jpg
  Tesla HomePage Clone/model-S.jpg
  Tesla HomePage Clone/model-X.jpg
  Tesla HomePage Clone/model-Y.jpg
  Tesla HomePage Clone/script.js
  Tesla HomePage Clone/style-1.css
  Tesla HomePage Clone/style-2.css
  Tesla HomePage Clone/tesla-logo.svg
Labels: Level2, GSSoC22, ready-to-merge

#810 Added Reddit Clone files
  Reddit_Clone/assets/css/style.css
  Reddit_Clone/assets/media/Capture.PNG
  Reddit_Clone/assets/media/Icons/cat0.PNG
  Reddit_Clone/assets/media/Icons/cat1.PNG
  Reddit_Clone/assets/media/Icons/cat2.PNG
  Reddit_Clone/assets/media/Icons/cat3.PNG
  Reddit_Clone/assets/media/Icons/cat4.PNG
  Reddit_Clone/assets/media/Icons/cat5.PNG
  Reddit_Clone/assets/media/Icons/header0.PNG
  Reddit_Clone/assets/media/Icons/header1.PNG
  Reddit_Clone/assets/media/Icons/header2.PNG
  Reddit_Clone/assets/media/Icons/header3.PNG
  Reddit_Clone/assets/media/Icons/header4.PNG
  Reddit_Clone/assets/media/Icons/header5.PNG
  Reddit_Clone/assets/media/Icons/header6.PNG
  Reddit_Clone/assets/media/Icons/header7.PNG
  Reddit_Clone/assets/media/Icons/header8.PNG
  Reddit_Clone/assets/media/Icons/newpost0.PNG
  Reddit_Clone/assets/media/Icons/newpost1.PNG
  Reddit_Clone/assets/media/avatar.png
  Reddit_Clone/assets/media/icon.png
  Reddit_Clone/assets/media/side-nav/0.png
  Reddit_Clone/assets/media/side-nav/1.png
  Reddit_Clone/index.html
  Reddit_Clone/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#805 Added Fibonacci checker
  Fibonacci checker/Fibonacci.css
  Fibonacci checker/Fibonacci.html
  Fibonacci checker/Fibonacci.js
  Fibonacci checker/bgi5.jpg
  Fibonacci checker/readme
  Fibonacci checker/ss1.png
Labels: Level2, GSSoC22, ready-to-merge

#748 Flipkart UI Clone
  Flipkart UI Clone/flipkart.css
  Flipkart UI Clone/flipkart.html
  Flipkart UI Clone/flipkart.js
  Flipkart UI Clone/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#753 adding custom color picker
  Color Picker/assets/color-picker.png
  Color Picker/font/sans.ttf
  Color Picker/index.html
  Color Picker/readme.md
  Color Picker/script.js
  Color Picker/style.css
Labels: Level1, GSSoC22, ready-to-merge

#835 Online Scarf Store
  Online Scarf Store/3.jpg
  Online Scarf Store/README.md
  Online Scarf Store/images/3.jpg
  Online Scarf Store/index.html
  Online Scarf Store/logoh.jpg
Labels: Level2, GSSoC22, ready-to-merge

#825 Added Infinity Scroll
  Infinity Scroll/IMG/bars.svg
  Infinity Scroll/README.md
  Infinity Scroll/index.html
  Infinity Scroll/main.js
  Infinity Scroll/style.less
  Infinity Scroll/styling.css
Labels: Level2, GSSoC22

#833 portfolio webpage
  Portfolio webpage/README.md
  Portfolio webpage/about.html
  Portfolio webpage/animate.css
  Portfolio webpage/contact.html
  Portfolio webpage/index.html
  Portfolio webpage/preview.png
  Portfolio webpage/project.html
  Portfolio webpage/style.css
  Portfolio webpage/t.min.js
  Portfolio webpage/work.html
  Portfolio webpage/wow.min.js
Labels: Level2, GSSoC22, ready-to-merge

#807 Generate Random Name
  Generate Random Names/index.html
  Generate Random Names/readme.md
  Generate Random Names/script.js
  Generate Random Names/style.css
Labels: Level1, GSSoC22, ready-to-merge

#781 Google Login Page
  Google Login Page/google.png
  Google Login Page/index.html
  Google Login Page/readme.md
  Google Login Page/style.css
Labels: Level2, GSSoC22, ready-to-merge

#891 Template updated
  .docs/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/add-project.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level1, GSSoC22

#888 Bookmark Saver
  Bookmark Saver/README.md
  Bookmark Saver/index.html
  Bookmark Saver/script.js
  Bookmark Saver/style.css
Labels: Level2, GSSoC22

#882 Added Scramble Game
  Scramble Game/index.html
  Scramble Game/script.js
  Scramble Game/style.css
Labels: Level1, GSSoC22, ready-to-merge

#881 Added Arduino Website Clone files
  Arduino_Website_Clone/assets/css/style.css
  Arduino_Website_Clone/assets/media/Capture.PNG
  Arduino_Website_Clone/assets/media/action_cards/LED.svg
  Arduino_Website_Clone/assets/media/action_cards/career.svg
  Arduino_Website_Clone/assets/media/action_cards/cart.svg
  Arduino_Website_Clone/assets/media/action_cards/cloud.svg
  Arduino_Website_Clone/assets/media/action_cards/donate.svg
  Arduino_Website_Clone/assets/media/arduino-UNO.png
  Arduino_Website_Clone/assets/media/events/00.png
  Arduino_Website_Clone/assets/media/events/01.jpg
  Arduino_Website_Clone/assets/media/events/02.jpg
  Arduino_Website_Clone/assets/media/events/03.png
  Arduino_Website_Clone/assets/media/icon.png
  Arduino_Website_Clone/index.html
  Arduino_Website_Clone/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#879 Added TicTacToe
  Tic-Tac-Toe Game/README.md
  Tic-Tac-Toe Game/index.html
  Tic-Tac-Toe Game/script.js
  Tic-Tac-Toe Game/style.css
  Tic-Tac-Toe Game/tictactoe-dark.png
  Tic-Tac-Toe Game/tictactoe-light.png
Labels: Level2, GSSoC22, ready-to-merge

#849 Added CocaCola landing page
  CocaCola_LandingPage/README.md
  CocaCola_LandingPage/img/close.png
  CocaCola_LandingPage/img/cocacola1.png
  CocaCola_LandingPage/img/cocacola2.png
  CocaCola_LandingPage/img/cocacola3.png
  CocaCola_LandingPage/img/cocacola4.png
  CocaCola_LandingPage/img/cocacola5.png
  CocaCola_LandingPage/img/cocacola6.png
  CocaCola_LandingPage/img/logo.png
  CocaCola_LandingPage/img/menu.png
  CocaCola_LandingPage/index.html
  CocaCola_LandingPage/style.css
Labels: Level2, GSSoC22, ready-to-merge

#875 Added Lyrics Finder
  LyricsFinder/index.html
  LyricsFinder/readme.md.txt
  LyricsFinder/script.js
  LyricsFinder/spotify-logo-png-7057.png
  LyricsFinder/style.css
  LyricsFinder/—Pngtree—mockup smartphone mobile png_5810614.png
Labels: Level2, GSSoC22, ready-to-merge

#872 there goes the box
  there goes the box/.vscode/settings.json
  there goes the box/README.md
  there goes the box/index.html
  there goes the box/preview.png
  there goes the box/style.css
Labels: Level1, GSSoC22, ready-to-merge

#867 Home-made Products selling website
  Home-made products selling website/README.md
  Home-made products selling website/css/style.css
  Home-made products selling website/images/1.jpg
  Home-made products selling website/images/2.jpg
  Home-made products selling website/images/3.png
  Home-made products selling website/images/4.jpg
  Home-made products selling website/images/5.jpg
  Home-made products selling website/images/Flipkart.webp
  Home-made products selling website/images/Myntra_logo.png
  Home-made products selling website/images/amazon.jpg
  Home-made products selling website/images/bags.jpg
  Home-made products selling website/images/bangels.jpg
  Home-made products selling website/images/bg.jpg
  Home-made products selling website/images/cosmatics.jpg
  Home-made products selling website/images/logos.jpg
  Home-made products selling website/images/meesho.png
  Home-made products selling website/images/shampoo.jpg
  Home-made products selling website/images/spices.jpg
  Home-made products selling website/index.html
Labels: Level2, GSSoC22, ready-to-merge

#865 added tip calculator
  tip calculator1/.gitignore
  tip calculator1/design/active-states.jpg
  tip calculator1/design/desktop-design-completed.jpg
  tip calculator1/design/desktop-design-empty.jpg
  tip calculator1/design/desktop-preview.jpg
  tip calculator1/design/mobile-design.jpg
  tip calculator1/images/favicon-32x32.png
  tip calculator1/images/icon-dollar.svg
  tip calculator1/images/icon-person.svg
  tip calculator1/images/logo.svg
  tip calculator1/index.html
  tip calculator1/index.js
  tip calculator1/readme.md
  tip calculator1/style.css
Labels: Level2, GSSoC22, ready-to-merge

#710 Twitter Login Page Clone
  Twitter Login Page/index.html
  Twitter Login Page/pattern.png
  Twitter Login Page/readme.md
  Twitter Login Page/style.css
Labels: Level2, GSSoC22, ready-to-merge

#830 Added Ascii value Generator
  Ascii Generator/Ascii.css
  Ascii Generator/Ascii.html
  Ascii Generator/Ascii.js
  Ascii Generator/bgi5.jpg
  Ascii Generator/readme
  Ascii Generator/ss1.png
  Ascii Generator/ss2.png
  Factorial Caluclator/Factorial.css
  Factorial Caluclator/Factorial.html
  Factorial Caluclator/Factorial.js
  Factorial Caluclator/bgi.png
  Factorial Caluclator/readme
Labels: Level2, GSSoC22, ready-to-merge

#828 Sentiment Analyzer Web App added
  Sentiment Analyzer Web App/README.md
  Sentiment Analyzer Web App/index.html
  Sentiment Analyzer Web App/sketch.js
  Sentiment Analyzer Web App/style.css
Labels: Level2, GSSoC22, ready-to-merge

#857 Incorder and decoder
  Incoder and Decoder/README.md
  Incoder and Decoder/css/style.css
  Incoder and Decoder/img/000.1.png
  Incoder and Decoder/img/000.2.png
  Incoder and Decoder/img/add-readme (1).png
  Incoder and Decoder/index.html
  Incoder and Decoder/js/script.js
Labels: GSSoC22, Level3, changes

#878 Added ZORO.to Clone files
  Zoro.to Clone/css/home.css
  Zoro.to Clone/images/add-readme (1).png
  Zoro.to Clone/images/logo.png
  Zoro.to Clone/images/screenshot.png
  Zoro.to Clone/images/zoro-bg.jpg
  Zoro.to Clone/images/zoro.png
  Zoro.to Clone/index.html
  Zoro.to Clone/readme.md
Labels: Level1, GSSoC22, ready-to-merge

#899 Added porfolio
  AnimatedPortfolio/astronaut_PNG29.png
  AnimatedPortfolio/style.css
  AnimatedPortfolio/text.html
  AnimatedPortfolio/ufo_PNG71675.png
  AnimatedPortfolio/—Pngtree—earth cartoon png material_5472758.png
Labels: Level1, GSSoC22, ready-to-merge

#904 Transparent Login page
  Transparent Login Page/Login page project/Documents - Shortcut.lnk
  Transparent Login Page/Login page project/bg.jpg
  Transparent Login Page/Login page project/index.css
  Transparent Login Page/Login page project/index.html
  Transparent Login Page/README.md
Labels: Level1, GSSoC22, ready-to-merge

#903 Added Factorial Of Numbers
  Factorial Of Numbers/Factorial.css
  Factorial Of Numbers/Factorial.html
  Factorial Of Numbers/Factorial.js
  Factorial Of Numbers/bgi.png
  Factorial Of Numbers/readme
Labels: Level1, GSSoC22, ready-to-merge

#906 adding name plate generator
  Name Plate Generator/app.js
  Name Plate Generator/index.html
  Name Plate Generator/readme.md
  Name Plate Generator/style.css
Labels: Level1, GSSoC22

#911 Long Drive
  Long Drive/README.md
  Long Drive/index.html
  Long Drive/style.css
Labels: Level1, GSSoC22

#920 feat: browser detector added
  Browser Detector/README.md.md
  Browser Detector/img/brave.png
  Browser Detector/img/chrome.png
  Browser Detector/img/download.jfif
  Browser Detector/img/edge.png
  Browser Detector/img/opera.png
  Browser Detector/index.html
  Browser Detector/styles.css
Labels: Level2, GSSoC22

#921 Added Adobe_Website_Clone files
  Adobe_Clone/assets/css/style.css
  Adobe_Clone/assets/media/Capture.PNG
  Adobe_Clone/assets/media/Carousel/1.png
  Adobe_Clone/assets/media/Carousel/2.jpg
  Adobe_Clone/assets/media/Carousel/3_1.jpg
  Adobe_Clone/assets/media/Carousel/3_2.png
  Adobe_Clone/assets/media/Carousel/4.jpg
  Adobe_Clone/assets/media/icon.ico
  Adobe_Clone/assets/media/summit.jpg
  Adobe_Clone/index.html
  Adobe_Clone/readme.md
Labels: Level2, GSSoC22

#676 Temperature Convereter Website
  Falling_Ball_Game/index.html
  Falling_Ball_Game/script.js
  Falling_Ball_Game/style.css
  Temperature-Converter-Website/README.md
  Temperature-Converter-Website/index.html
  Temperature-Converter-Website/script.js
  Temperature-Converter-Website/style.css
Labels: Level2, GSSoC22, changes

#913 Scratch Card Application🧩
  Income Tax Calculator/script.js
  Scratch Card Application/Images/Gpay_Card 1.jpg
  Scratch Card Application/Images/Gpay_Card 2.jpg
  Scratch Card Application/Images/Gpay_Card 3.jpg
  Scratch Card Application/Images/Gpay_Card 4.jpg
  Scratch Card Application/Images/front.jpg
  Scratch Card Application/Scratchpad.min.js
  Scratch Card Application/app.js
  Scratch Card Application/index.html
  Scratch Card Application/readme.md
  Scratch Card Application/style.css
Labels: Level1, GSSoC22

#953 adding election map
  Election Map/index.html
  Election Map/readme.md
  Election Map/script.js
  Election Map/style.css
Labels: GSSoC22, Level3, ready-to-merge
