Repository khushi-purwar/WebDev-ProjectKart, pull requests merged in 2022-05, with the labels that each got.

#1097 Password Validation
  Password Validation/Readme
  Password Validation/index.html
  Password Validation/script.js
  Password Validation/style.css
Labels: Level2, GSSoC22

#1096 Random Advice Generator
  Random Advice generator/Readme
  Random Advice generator/index.html
  Random Advice generator/script.js
Labels: Level1, GSSoC22

#1090 Height Converter
  Height Converter/Readme
  Height Converter/index.html
  Height Converter/script.js
  Height Converter/style.css
Labels: Level2, GSSoC22

#1099 Palindrome checker
  Palindrome Checker Website/palindrome.css
  Palindrome Checker Website/palindrome.html
  Palindrome Checker Website/palindrome.js
  Palindrome Checker Website/readme.md
Labels: Level2, GSSoC22

#1111 Issue 1085-Created Landing Page of a Gym Webste
  CrossfitPlanet-LandingPage/Assets/A.png
  CrossfitPlanet-LandingPage/Assets/B.png
  CrossfitPlanet-LandingPage/Assets/C.png
  CrossfitPlanet-LandingPage/Assets/gym.jpg
  CrossfitPlanet-LandingPage/Assets/gym.png
  CrossfitPlanet-LandingPage/index.html
  CrossfitPlanet-LandingPage/readme.md
  CrossfitPlanet-LandingPage/style.css
  CrossfitPlanet-LandingPage/timer.js
  CrossfitPlanet-LandingPage/utils.css
Labels: Level2, GSSoC22, ready-to-merge

#1136 Budget App
  Budget App/css/all.css
  Budget App/css/bootstrap.min.css
  Budget App/css/main.css
  Budget App/index.html
  Budget App/js/app.js
  Budget App/js/bootstrap.bundle.min.js
  Budget App/js/jquery-3.3.1.min.js
  Budget App/readme.md
  Budget App/webfonts/fa-brands-400.eot
  Budget App/webfonts/fa-brands-400.svg
  Budget App/webfonts/fa-brands-400.ttf
  Budget App/webfonts/fa-brands-400.woff
  Budget App/webfonts/fa-brands-400.woff2
  Budget App/webfonts/fa-regular-400.eot
  Budget App/webfonts/fa-regular-400.svg
  Budget App/webfonts/fa-regular-400.ttf
  Budget App/webfonts/fa-regular-400.woff
  Budget App/webfonts/fa-regular-400.woff2
  Budget App/webfonts/fa-solid-900.eot
  Budget App/webfonts/fa-solid-900.svg
  Budget App/webfonts/fa-solid-900.ttf
  Budget App/webfonts/fa-solid-900.woff
  Budget App/webfonts/fa-solid-900.woff2
Labels: GSSoC22, Level3

#1116 wall breaker
  wall breaker/ball.js
  wall breaker/brick.js
  wall breaker/index.html
  wall breaker/paddle.js
Labels: GSSoC22, Level3, ready-to-merge

#1126 Syntra Digital Agency UI added
  Syntra Digital Agency UI/README.md
  Syntra Digital Agency UI/package.json
  Syntra Digital Agency UI/public/favicon.ico
  Syntra Digital Agency UI/public/index.html
  Syntra Digital Agency UI/public/logo192.png
  Syntra Digital Agency UI/public/logo512.png
  Syntra Digital Agency UI/public/manifest.json
  Syntra Digital Agency UI/public/robots.txt
  Syntra Digital Agency UI/src/App.css
  Syntra Digital Agency UI/src/App.js
  Syntra Digital Agency UI/src/App.test.js
  Syntra Digital Agency UI/src/components/AboutUs.jsx
  Syntra Digital Agency UI/src/components/Analytics.jsx
  Syntra Digital Agency UI/src/components/Blog.jsx
  Syntra Digital Agency UI/src/components/ChooseUs.jsx
  Syntra Digital Agency UI/src/components/Client.jsx
  Syntra Digital Agency UI/src/components/Footer.jsx
  Syntra Digital Agency UI/src/components/Heading.jsx
  Syntra Digital Agency UI/src/components/SDA.jsx
  Syntra Digital Agency UI/src/components/SDAleft.jsx
  Syntra Digital Agency UI/src/components/SDAright.jsx
  Syntra Digital Agency UI/src/components/img1.png
  Syntra Digital Agency UI/src/components/img2.png
  Syntra Digital Agency UI/src/components/img3.png
  Syntra Digital Agency UI/src/components/img4.png
  Syntra Digital Agency UI/src/components/img5.png
  Syntra Digital Agency UI/src/components/logo.PNG
  Syntra Digital Agency UI/src/components/wave.png
  Syntra Digital Agency UI/src/components/wave1.png
  Syntra Digital Agency UI/src/components/wave3.png
  Syntra Digital Agency UI/src/index.css
  Syntra Digital Agency UI/src/index.js
  Syntra Digital Agency UI/src/reportWebVitals.js
  Syntra Digital Agency UI/src/setupTests.js
  Syntra Digital Agency UI/src/wave2.png
  Syntra Digital Agency UI/src/wave4.png
Labels: GSSoC22, Level3, ready-to-merge

#1145 Flip Card Game
  Flip Card Game/README.md
  Flip Card Game/css/style.css
  Flip Card Game/img/Web capture_2-5-2022_221757_127.0.0.1.jpeg
  Flip Card Game/img/add-read.png
  Flip Card Game/img/ainesy190100008.jpg
  Flip Card Game/index.html
  Flip Card Game/js/script.js
Labels: Level2, GSSoC22

#1110 Added COVID-19 Blog site
  Covid-19/README.md
  Covid-19/assests/img/01.png
  Covid-19/assests/img/02.png
  Covid-19/assests/img/03.png
  Covid-19/assests/img/04.png
  Covid-19/assests/img/05.png
  Covid-19/assests/img/06.png
  Covid-19/assests/img/about.svg
  Covid-19/assests/img/blog-1.svg
  Covid-19/assests/img/blog-2.svg
  Covid-19/assests/img/blog-3.svg
  Covid-19/assests/img/exp-1.png
  Covid-19/assests/img/exp-2.png
  Covid-19/assests/img/exp-3.png
  Covid-19/assests/img/exp-4.png
  Covid-19/assests/img/home-bg.png
  Covid-19/assests/img/home.svg
  Covid-19/assests/style-c.css
  Covid-19/index.html
  Covid-19/script/script-c.js
Labels: GSSoC22, Level3, ready-to-merge

#1135 Weight Converter
  Weight Converter/index.html
  Weight Converter/readme.md
  Weight Converter/script.js
  Weight Converter/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1140 Added Automorphic Number Checker
  Automorphic Number Checker/Readme.md
  Automorphic Number Checker/index.html
  Automorphic Number Checker/script/script.js
  Automorphic Number Checker/snips/snip1.png
  Automorphic Number Checker/style/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1152 Book Store
  Book_Store/SearchString.js
  Book_Store/books/AliceInWonderland.txt
  Book_Store/books/JekyllAndHyde.txt
  Book_Store/books/LOTR.txt
  Book_Store/index.html
  Book_Store/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1150 adding github profile
  github-profiles/index.html
  github-profiles/scripts/init.js
  github-profiles/scripts/main.js
  github-profiles/styles/styles.css
Labels: Level2, GSSoC22, ready-to-merge

#1157 Moto Racing🚗
  Moto Racing/bg.jpg
  Moto Racing/index.html
  Moto Racing/jumpsound.mp3
  Moto Racing/readme.md
  Moto Racing/script.js
  Moto Racing/style.css
  Moto Racing/th (3).jfif
  Moto Racing/th (4).jfif
Labels: Level2, GSSoC22, ready-to-merge

#1123 Vowel counter
  Vowel Counter/Index.html
  Vowel Counter/Readme.md
  Vowel Counter/script.js
  Vowel Counter/style.css
Labels: Level2, GSSoC22

#1125 Form Validation
  Form Validation/Readme.md
  Form Validation/index.html
  Form Validation/script.js
  Form Validation/style.css
Labels: Level2, GSSoC22

#1118 Interview bit website clone
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/AWS-Salary.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/C__Interview-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Client-Server-Model.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Deloitte-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/DevOps-Projects.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/HTML-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/IBM-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Infosys-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Kubectl-Commands.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Machine_Learning-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Mindtree-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/MySQL-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Node_js-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/OS-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Pyspark-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Python-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Rest_API-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/SAP_ABAP-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Types-of-Computer-Networks.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Types-of-Data-Analytics.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Types-of-Network-Topology.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/Types-of-Software-Testing.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/ZOHO-01.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/banner-2.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/brand-inv.0d6c8a.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/coins.5e3257.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/css.css
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/discord.433ae0.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/fallback_company.993a11.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/fallback_technology.094c57.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/java.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/logo.87a398.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/mock-interview.89e0db.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/r-projects.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/score-icon.56850b.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/streak.f9a8ad.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/student.04de57.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/target.b00165.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/types-of-Databases.png
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/user-type.60ae89.svg
  Interview Bit Website Clone/Coding Practice _ Coding Challenges - InterviewBit_files/working-professional.e692df.svg
  Interview Bit Website Clone/index.html
  Interview Bit Website Clone/readme.md
Labels: GSSoC22, Level3

#1130 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSoC22, ready-to-merge, Level0

#1124 Detect key and Keycode
  Detect key and Keycode/Readme.md
  Detect key and Keycode/index.html
  Detect key and Keycode/script.js
  Detect key and Keycode/style.css
Labels: GSSoC22, changes

#1180 Movie seat booking
  movie-seat-booking/README.md
  movie-seat-booking/index.html
  movie-seat-booking/script.js
  movie-seat-booking/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1186 weather application using vue js
  Weather application using vue js/babel.config.js
  Weather application using vue js/package.json
  Weather application using vue js/src/App.vue
  Weather application using vue js/src/assets/logo.png
  Weather application using vue js/src/assets/main.txt
  Weather application using vue js/src/assets/mars.webp
  Weather application using vue js/src/assets/mars2.webp
  Weather application using vue js/src/assets/mobilebackdrop.jpg
  Weather application using vue js/src/main.js
Labels: GSSoC22, Level3

#1131 Added Happy Number Checker
  Happy Number Checker/Readme.md
  Happy Number Checker/index.html
  Happy Number Checker/script/script.js
  Happy Number Checker/snips/snip.png
  Happy Number Checker/style/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1127 Leap year checker
  Leap Year Checeker/bgi5.jpg
  Leap Year Checeker/leap.css
  Leap Year Checeker/leap.html
  Leap Year Checeker/leap.js
  Leap Year Checeker/readme.md
Labels: Level1, GSSoC22, ready-to-merge

#1193 Take A Screenshot🎥
  Take A Screenshot/index.html
  Take A Screenshot/readme.md
  Take A Screenshot/script.js
  Take A Screenshot/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1194 Adding drawing app
  drawing-app/index.html
  drawing-app/script.js
  drawing-app/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1209 Update style.css
  Candy Brick Game/style.css
Labels: Level2, GSSoC22

#1210 Recipes for you-The Recipe Book
  The Recipe Book/add-recipe.html
  The Recipe Book/add-recipe.js
  The Recipe Book/app.js
  The Recipe Book/edit-recipe.html
  The Recipe Book/edit-recipe.js
  The Recipe Book/favicon.png
  The Recipe Book/index.html
  The Recipe Book/readme.md
  The Recipe Book/recipe-functions.js
  The Recipe Book/styles.css
  The Recipe Book/uuidv4.js
Labels: GSSoC22, Level3, ready-to-merge

#1211 Added Dino Game
  Dino-Game/assets/block.png
  Dino-Game/assets/cloud.jpg
  Dino-Game/assets/dino.png
  Dino-Game/assets/road.png
  Dino-Game/index.html
  Dino-Game/main.js
  Dino-Game/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1212 Breakout Game
  Breakout Game/assets/Web capture_4-5-2022_122539_127.0.0.1.jpeg
  Breakout Game/assets/style.css
  Breakout Game/index.html
  Breakout Game/readme.md
  Breakout Game/script/index.js
Labels: Level2, GSSoC22, ready-to-merge

#1220 feat: relaxation app added
  relaxer-app/README.md.md
  relaxer-app/app.js
  relaxer-app/med.html
  relaxer-app/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1238 Added String Anagram Checker
  String Anagram Checker/Readme.md
  String Anagram Checker/index.html
  String Anagram Checker/script/script.js
  String Anagram Checker/snips/snip1.png
  String Anagram Checker/style/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1240 portfolio template 2.0
  Portfolio template 2/index.css
  Portfolio template 2/index.html
  Portfolio template 2/index.js
Labels: GSSoC22, Level3, ready-to-merge

#1239 To Do App
  To-Do List/README.md
  To-Do List/assests/style.css
  To-Do List/index.html
  To-Do List/script/app.js
Labels: Level2, GSSoC22, changes

#1242 Issue #1202 resolved: Alarm App
  Alarm App/app.js
  Alarm App/index.html
  Alarm App/readme.md
  Alarm App/style.css
Labels: Level2, GSSoC22

#1244 Poll UI
  Poll UI/index.html
  Poll UI/readme.md
  Poll UI/script.js
  Poll UI/style.css
Labels: Level2, GSSoC22

#1237 Netflix Clone
  Netflix Clone/.firebase/hosting.YnVpbGQ
  Netflix Clone/.firebaserc
  Netflix Clone/.gitignore
  Netflix Clone/README.md
  Netflix Clone/firebase.json
  Netflix Clone/package.json
  Netflix Clone/public/favicon.ico
  Netflix Clone/public/index.html
  Netflix Clone/public/logo192.png
  Netflix Clone/public/logo512.png
  Netflix Clone/public/manifest.json
  Netflix Clone/public/robots.txt
  Netflix Clone/src/App.css
  Netflix Clone/src/App.js
  Netflix Clone/src/Cover.css
  Netflix Clone/src/Cover.js
  Netflix Clone/src/Dialogb.css
  Netflix Clone/src/Dialogb.js
  Netflix Clone/src/Movieslist.js
  Netflix Clone/src/Navbar.css
  Netflix Clone/src/Navbar.js
  Netflix Clone/src/Rows.css
  Netflix Clone/src/Rows.js
  Netflix Clone/src/axios.js
  Netflix Clone/src/index.css
  Netflix Clone/src/index.js
  Netflix Clone/src/serviceWorker.js
  Netflix Clone/src/setupTests.js
Labels: GSSoC22, Level3

#1245 Added Special Number Checker
  Special Number Checker/Readme.md
  Special Number Checker/index.html
  Special Number Checker/script/script.js
  Special Number Checker/snips/snip1.png
  Special Number Checker/style/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1251 Sound Classifier added
  Sound Classifier/README.md
  Sound Classifier/package.json
  Sound Classifier/public/favicon.ico
  Sound Classifier/public/index.html
  Sound Classifier/public/logo192.png
  Sound Classifier/public/logo512.png
  Sound Classifier/public/manifest.json
  Sound Classifier/public/robots.txt
  Sound Classifier/src/App.css
  Sound Classifier/src/App.js
  Sound Classifier/src/App.test.js
  Sound Classifier/src/components/AudioClassifier/AudioClassifier.css
  Sound Classifier/src/components/AudioClassifier/AudioClassifier.js
  Sound Classifier/src/components/Footer/Footer.css
  Sound Classifier/src/components/Footer/Footer.js
  Sound Classifier/src/index.css
  Sound Classifier/src/index.js
  Sound Classifier/src/logo.svg
  Sound Classifier/src/reportWebVitals.js
  Sound Classifier/src/setupTests.js
Labels: GSSoC22, Level3

#1253 Added Language Translator
  41. Language Translator/Language Translator.png
  41. Language Translator/country.js
  41. Language Translator/index.html
  41. Language Translator/script.js
  41. Language Translator/style.css
  index.html
Labels: Level2, GSSoC22, ready-to-merge

#1258 Face Recognition using ReactJS
  Face Recognition Using ReactJS/package.json
  Face Recognition Using ReactJS/public/favicon.png
  Face Recognition Using ReactJS/public/index.html
  Face Recognition Using ReactJS/public/logo192.png
  Face Recognition Using ReactJS/public/manifest.json
  Face Recognition Using ReactJS/public/robots.txt
  Face Recognition Using ReactJS/readme.md
  Face Recognition Using ReactJS/src/App.css
  Face Recognition Using ReactJS/src/App.js
  Face Recognition Using ReactJS/src/App.test.js
  Face Recognition Using ReactJS/src/Components/FaceDetect.js
  Face Recognition Using ReactJS/src/Components/Input-form.js
  Face Recognition Using ReactJS/src/Components/Logo.css
  Face Recognition Using ReactJS/src/Components/Logo.js
  Face Recognition Using ReactJS/src/Components/Navigation.js
  Face Recognition Using ReactJS/src/Components/Rank.js
  Face Recognition Using ReactJS/src/Components/Register/Register.js
  Face Recognition Using ReactJS/src/Components/SignIn/SignIn.js
  Face Recognition Using ReactJS/src/Components/faceDetect.css
  Face Recognition Using ReactJS/src/Components/logo.svg
  Face Recognition Using ReactJS/src/index.css
  Face Recognition Using ReactJS/src/index.js
  Face Recognition Using ReactJS/src/reportWebVitals.js
  Face Recognition Using ReactJS/src/setupTests.js
Labels: GSSoC22, Level3, ready-to-merge

#1266 Beauty Store -Website
  Beauty Store website/build/output.css
  Beauty Store website/css/style.css
  Beauty Store website/images/Cosmetics.png
  Beauty Store website/images/arrow-right.svg
  Beauty Store website/images/cosmetic-bottle.png
  Beauty Store website/images/cosmetic-cream.png
  Beauty Store website/images/cosmetics-bottles.png
  Beauty Store website/images/cosmetics-jar.png
  Beauty Store website/images/cosmetics-lady.png
  Beauty Store website/images/cosmetics-tools.png
  Beauty Store website/images/cosmetics-two-bottles.png
  Beauty Store website/images/cosmetics-yellow-jar.png
  Beauty Store website/images/facebook.svg
  Beauty Store website/images/instagram.svg
  Beauty Store website/images/logo.svg
  Beauty Store website/images/search.svg
  Beauty Store website/images/shopping-bag.svg
  Beauty Store website/images/twitter.svg
  Beauty Store website/images/user.svg
  Beauty Store website/index.html
  Beauty Store website/js/app.js
  Beauty Store website/package.json
Labels: GSSoC22, Level3, ready-to-merge

#1273 Exotic cars website added
  exotic cars homepage/all.min.css
  exotic cars homepage/banner.png
  exotic cars homepage/fa-brands-400.eot
  exotic cars homepage/fa-brands-400.svg
  exotic cars homepage/fa-brands-400.ttf
  exotic cars homepage/fa-brands-400.woff
  exotic cars homepage/fa-brands-400.woff2
  exotic cars homepage/fa-regular-400.eot
  exotic cars homepage/fa-regular-400.svg
  exotic cars homepage/fa-regular-400.ttf
  exotic cars homepage/fa-regular-400.woff
  exotic cars homepage/fa-regular-400.woff2
  exotic cars homepage/fa-solid-900.eot
  exotic cars homepage/fa-solid-900.svg
  exotic cars homepage/fa-solid-900.ttf
  exotic cars homepage/fa-solid-900.woff
  exotic cars homepage/fa-solid-900.woff2
  exotic cars homepage/index.html
  exotic cars homepage/logo.png
  exotic cars homepage/style.css
Labels: GSSoC22, Level3

#1280 Character counter
  Character counter/Readme.md
  Character counter/index.html
  Character counter/script.js
  Character counter/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1279 Country-tour
  Country-tour/Readme.md
  Country-tour/index.html
  Country-tour/script.js
  Country-tour/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1272 Gotham blog website
  Gotham blog website/ProximaNova-Bold.ttf
  Gotham blog website/ProximaNova-Bold.woff
  Gotham blog website/ProximaNova-Light.ttf
  Gotham blog website/ProximaNova-Light.woff
  Gotham blog website/ProximaNova-Regular.ttf
  Gotham blog website/ProximaNova-Regular.woff
  Gotham blog website/Roboto-Light.ttf
  Gotham blog website/Roboto-Light.woff
  Gotham blog website/Roboto-Regular.ttf
  Gotham blog website/Roboto-Regular.woff
  Gotham blog website/all.css
  Gotham blog website/article-1.jpg
  Gotham blog website/article-2.jpg
  Gotham blog website/article-3.jpg
  Gotham blog website/article-4.jpg
  Gotham blog website/article-5.jpg
  Gotham blog website/fa-brands-400.eot
  Gotham blog website/fa-brands-400.svg
  Gotham blog website/fa-brands-400.ttf
  Gotham blog website/fa-brands-400.woff
  Gotham blog website/fa-brands-400.woff2
  Gotham blog website/fa-regular-400.eot
  Gotham blog website/fa-regular-400.svg
  Gotham blog website/fa-regular-400.ttf
  Gotham blog website/fa-regular-400.woff
  Gotham blog website/fa-regular-400.woff2
  Gotham blog website/fa-solid-900.eot
  Gotham blog website/fa-solid-900.svg
  Gotham blog website/fa-solid-900.ttf
  Gotham blog website/fa-solid-900.woff
  Gotham blog website/fa-solid-900.woff2
  Gotham blog website/galaxy-s8-gcc0eb4a11_1920.jpg
  Gotham blog website/index.html
  Gotham blog website/iphone-12-g6c7820aac_1920.jpg
  Gotham blog website/logo.png
  Gotham blog website/playstation-g0e42e9427_1920.jpg
  Gotham blog website/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1257 Added E-commerce website
  E-Commerce Website/C.jpg
  E-Commerce Website/Images/alert-circle-outline.svg
  E-Commerce Website/Images/body-outline.svg
  E-Commerce Website/Images/call-outline.svg
  E-Commerce Website/Images/cart-outline.svg
  E-Commerce Website/Images/checkmark-circle-outline.svg
  E-Commerce Website/Images/document-text-outline.svg
  E-Commerce Website/Images/fitness-outline.svg
  E-Commerce Website/Images/help-circle-outline.svg
  E-Commerce Website/Images/help-outline.svg
  E-Commerce Website/Images/home-outline.svg
  E-Commerce Website/Images/log-in-outline.svg
  E-Commerce Website/Images/log-out-outline.svg
  E-Commerce Website/Images/mail-open-outline.svg
  E-Commerce Website/Images/moon-outline.svg
  E-Commerce Website/Images/musical-notes-outline.svg
  E-Commerce Website/Images/online-shopping.png
  E-Commerce Website/Images/person-add-outline.svg
  E-Commerce Website/Images/person-circle-outline.svg
  E-Commerce Website/Images/person-remove-outline.svg
  E-Commerce Website/Images/phone-portrait-outline.svg
  E-Commerce Website/Images/planet-outline.svg
  E-Commerce Website/Images/sunny-outline.svg
  E-Commerce Website/Readme.md
  E-Commerce Website/cart.html
  E-Commerce Website/ecom.css
  E-Commerce Website/ecom.js
  E-Commerce Website/index.html
  E-Commerce Website/login.html
  E-Commerce Website/phones.html
Labels: GSSoC22, Level3, ready-to-merge

#1264 Markdown Blog
  Markdown blog/.gitignore
  Markdown blog/README.md
  Markdown blog/components/layout.js
  Markdown blog/next.config.js
  Markdown blog/package-lock.json
  Markdown blog/package.json
  Markdown blog/pages/_app.js
  Markdown blog/pages/index.js
  Markdown blog/pages/post/[slug].js
  Markdown blog/postcss.config.js
  Markdown blog/posts/Longest-Common-Prefix.md
  Markdown blog/posts/Maximum-Depth-of-Binary-Tree.md
  Markdown blog/posts/Merge-k-Sorted-Lists.md
  Markdown blog/posts/Roman-to-Integer.md
  Markdown blog/posts/Simple-Number.md
  Markdown blog/posts/Valid-Palindrome.md
  Markdown blog/public/favicon.ico
  Markdown blog/public/images/03-10-2021.jpg
  Markdown blog/public/images/04-10-2021.jpg
  Markdown blog/public/images/11-12-2021.jpg
  Markdown blog/public/images/22-09-2021.jpg
  Markdown blog/public/images/27-10-2021.jpg
  Markdown blog/public/images/leetcode-grinding-guide.jpg
  Markdown blog/public/vercel.svg
  Markdown blog/styles/globals.css
  Markdown blog/tailwind.config.js
Labels: GSSoC22, Level3

#1278 Google Photos Clone
  Google Photos Clone/README.md
  Google Photos Clone/package.json
  Google Photos Clone/public/index.html
  Google Photos Clone/public/manifest.json
  Google Photos Clone/public/robots.txt
  Google Photos Clone/src/App.js
  Google Photos Clone/src/actions/index.js
  Google Photos Clone/src/api/album.js
  Google Photos Clone/src/api/photo.js
  Google Photos Clone/src/components/Album.js
  Google Photos Clone/src/components/CreateAlbumModal.js
  Google Photos Clone/src/components/Login.js
  Google Photos Clone/src/components/Nav.js
  Google Photos Clone/src/components/Photo.js
  Google Photos Clone/src/css/App.css
  Google Photos Clone/src/css/HomePage.css
  Google Photos Clone/src/css/Nav.css
  Google Photos Clone/src/css/Photo.css
  Google Photos Clone/src/css/index.css
  Google Photos Clone/src/firebase.example.js
  Google Photos Clone/src/index.js
  Google Photos Clone/src/pages/AlbumPage.js
  Google Photos Clone/src/pages/HomePage.js
  Google Photos Clone/src/reducers/albumReducer.js
  Google Photos Clone/src/reducers/index.js
  Google Photos Clone/src/reducers/userReducer.js
  Google Photos Clone/src/store.js
Labels: GSSoC22, Level3

#1285 Fluid website
  Fluid-Webpage/README.md
  Fluid-Webpage/images/Thumbs.db
  Fluid-Webpage/images/background.png
  Fluid-Webpage/images/bubble.png
  Fluid-Webpage/images/fb.png
  Fluid-Webpage/images/ig.png
  Fluid-Webpage/images/info.png
  Fluid-Webpage/images/logo.png
  Fluid-Webpage/images/menu.png
  Fluid-Webpage/images/share.png
  Fluid-Webpage/images/tw.png
  Fluid-Webpage/index.html
  Fluid-Webpage/style.css
Labels: GSSoC22

#1286 Car Racing Game
  Car Racing Game/index.html
  Car Racing Game/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#1287 Mortgage Calculator
  Mortgage Calculator/index.html
  Mortgage Calculator/loancalculator.css
  Mortgage Calculator/loancalculator.js
  Mortgage Calculator/readme.md
Labels: Level2, GSSoC22

#1289 scooter website
  scooter website/.gitattributes
  scooter website/74499-circle.gif
  scooter website/Rectangle 4.png
  scooter website/Rectangle 5.png
  scooter website/Scooter Image 1.png
  scooter website/index.html
  scooter website/script.js
  scooter website/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1288 Number guessing game
  Number Guessing Game/README.md
  Number Guessing Game/index.html
  Number Guessing Game/script.js
  Number Guessing Game/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1290 Sortable List
  Sortable List/README.md
  Sortable List/css/style.css
  Sortable List/img/add-readme (1).png
  Sortable List/img/sortablelistss.png
  Sortable List/img/sortablelistss2.png
  Sortable List/index.html
  Sortable List/js/script.js
Labels: Level2, GSSoC22, ready-to-merge

#1296 Added GoogleDue_Clone files
  GoogleDuo_Clone/assets/css/style.css
  GoogleDuo_Clone/assets/media/Capture.PNG
  GoogleDuo_Clone/assets/media/avatar.png
  GoogleDuo_Clone/assets/media/bg.svg
  GoogleDuo_Clone/assets/media/duo.svg
  GoogleDuo_Clone/assets/media/icon.png
  GoogleDuo_Clone/assets/media/msg.png
  GoogleDuo_Clone/index.html
  GoogleDuo_Clone/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#1298 react weather app
  weather app using react js/.gitignore
  weather app using react js/README.md
  weather app using react js/netlify.toml
  weather app using react js/package.json
  weather app using react js/public/Logo.png
  weather app using react js/public/favicon.ico
  weather app using react js/public/index.html
  weather app using react js/public/logo192.png
  weather app using react js/public/logo512.png
  weather app using react js/public/manifest.json
  weather app using react js/public/robots.txt
  weather app using react js/src/App.css
  weather app using react js/src/App.js
  weather app using react js/src/Data.css
  weather app using react js/src/Data.js
  weather app using react js/src/Weather.css
  weather app using react js/src/Weather.js
  weather app using react js/src/images/Arrow.png
  weather app using react js/src/images/Clouds.jpg
  weather app using react js/src/images/Clouds.png
  weather app using react js/src/images/Cold.png
  weather app using react js/src/images/Haze.png
  weather app using react js/src/images/Hot.png
  weather app using react js/src/images/Sunrise.png
  weather app using react js/src/index.css
  weather app using react js/src/index.js
  weather app using react js/src/reportWebVitals.js
  weather app using react js/yarn.lock
Labels: GSSoC22, Level3, ready-to-merge

#1307 Piano
  Piano/README.md
  Piano/index.html
  Piano/script.js
  Piano/sounds/.DS_Store
  Piano/sounds/A3.mp3
  Piano/sounds/A4.mp3
  Piano/sounds/Ab3.mp3
  Piano/sounds/Ab4.mp3
  Piano/sounds/B3.mp3
  Piano/sounds/B4.mp3
  Piano/sounds/Bb3.mp3
  Piano/sounds/Bb4.mp3
  Piano/sounds/C3.mp3
  Piano/sounds/C4.mp3
  Piano/sounds/C5.mp3
  Piano/sounds/D3.mp3
  Piano/sounds/D4.mp3
  Piano/sounds/D5.mp3
  Piano/sounds/Db3.mp3
  Piano/sounds/Db4.mp3
  Piano/sounds/Db5.mp3
  Piano/sounds/E3.mp3
  Piano/sounds/E4.mp3
  Piano/sounds/E5.mp3
  Piano/sounds/Eb3.mp3
  Piano/sounds/Eb4.mp3
  Piano/sounds/Eb5.mp3
  Piano/sounds/F3.mp3
  Piano/sounds/F4.mp3
  Piano/sounds/G3.mp3
  Piano/sounds/G4.mp3
  Piano/sounds/Gb3.mp3
  Piano/sounds/Gb4.mp3
  Piano/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1308 NLP Question Answer App added
  NLP Question Answering App/README.md
  NLP Question Answering App/package.json
  NLP Question Answering App/public/favicon.ico
  NLP Question Answering App/public/index.html
  NLP Question Answering App/public/logo192.png
  NLP Question Answering App/public/logo512.png
  NLP Question Answering App/public/manifest.json
  NLP Question Answering App/public/robots.txt
  NLP Question Answering App/src/App.css
  NLP Question Answering App/src/App.js
  NLP Question Answering App/src/App.test.js
  NLP Question Answering App/src/index.css
  NLP Question Answering App/src/index.js
  NLP Question Answering App/src/logo.svg
  NLP Question Answering App/src/setupTests.js
Labels: GSSoC22, Level3

#1313 added Grocery Store readme
  Grocery store/readme.md
Labels: GSSoC22, Level0

#1309 Added Harshad Number Checker
  Harshad Number Checker/Readme.md
  Harshad Number Checker/index.html
  Harshad Number Checker/script/script.js
  Harshad Number Checker/snips/snip1.png
  Harshad Number Checker/style/style.css
Labels: GSSoC22, Level3

#1322 custom css scrollbar
  CSS scrollbar/README.md
  CSS scrollbar/index.html
Labels: Level2, GSSoC22

#1324 Maze Runner
  Maze Runner/.gitignore
  Maze Runner/index.html
  Maze Runner/mazerunner.js
  Maze Runner/style.css
  Maze Runner/survival.html
  Maze Runner/template.js
Labels: GSSoC22, Level3

#1329 Sling shot
  SlingShot/README.md
  SlingShot/game.js
  SlingShot/index.html
  SlingShot/matter.js
  SlingShot/styles.css
Labels: GSSoC22, Level3, ready-to-merge

#1328 Random meal
  Random-Meal-Generator/README.md
  Random-Meal-Generator/index.html
  Random-Meal-Generator/script.js
  Random-Meal-Generator/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1316 Our Fitness Website (Fully Responsive)
  Our Fitness/OurFitnessWebsite/dumbell.png
  Our Fitness/OurFitnessWebsite/gym.jpg
  Our Fitness/OurFitnessWebsite/gym.png
  Our Fitness/OurFitnessWebsite/index.html
  Our Fitness/OurFitnessWebsite/style.css
  Our Fitness/OurFitnessWebsite/timer.js
  Our Fitness/OurFitnessWebsite/utils.css
  Our Fitness/README.md
Labels: Level2, GSSoC22

#1332 Adding the music kit
  Music Kit/drum-kit/images/crash.png
  Music Kit/drum-kit/images/kick.png
  Music Kit/drum-kit/images/snare.png
  Music Kit/drum-kit/images/tom1.png
  Music Kit/drum-kit/images/tom2.png
  Music Kit/drum-kit/images/tom3.png
  Music Kit/drum-kit/images/tom4.png
  Music Kit/drum-kit/index.html
  Music Kit/drum-kit/index.js
  Music Kit/drum-kit/sounds/crash.mp3
  Music Kit/drum-kit/sounds/kick-bass.mp3
  Music Kit/drum-kit/sounds/snare.mp3
  Music Kit/drum-kit/sounds/tom-1.mp3
  Music Kit/drum-kit/sounds/tom-2.mp3
  Music Kit/drum-kit/sounds/tom-3.mp3
  Music Kit/drum-kit/sounds/tom-4.mp3
  Music Kit/drum-kit/styles.css
  Music Kit/guitar/images/favicon.ico
  Music Kit/guitar/images/guitar.png
  Music Kit/guitar/index.html
  Music Kit/guitar/index.js
  Music Kit/guitar/sounds/chordA.mp3
  Music Kit/guitar/sounds/chordB.mp3
  Music Kit/guitar/sounds/chordC.mp3
  Music Kit/guitar/sounds/chordD.mp3
  Music Kit/guitar/sounds/chordDm.mp3
  Music Kit/guitar/sounds/chordE.mp3
  Music Kit/guitar/sounds/chordF.mp3
  Music Kit/guitar/sounds/chordG.mp3
  Music Kit/guitar/styles.css
  Music Kit/images/drum.png
  Music Kit/images/favicon.ico
  Music Kit/images/guitar.png
  Music Kit/images/music-logo.png
  Music Kit/images/music-note.png
  Music Kit/images/tabla.png
  Music Kit/index.html
  Music Kit/styles.css
  Music Kit/tabla/images/tabla.jpg
  Music Kit/tabla/index.html
  Music Kit/tabla/index.js
  Music Kit/tabla/sounds/a.mp3
  Music Kit/tabla/sounds/b.mp3
  Music Kit/tabla/sounds/c.mp3
  Music Kit/tabla/sounds/d.mp3
  Music Kit/tabla/sounds/e.mp3
  Music Kit/tabla/sounds/f.mp3
  Music Kit/tabla/sounds/g.mp3
  Music Kit/tabla/styles.css
Labels: Level2, GSSoC22, ready-to-merge

#1337 Emoji Searcher or Generator
  Emoji Generator (Searcher)/README.md
  Emoji Generator (Searcher)/app.js
  Emoji Generator (Searcher)/index.css
  Emoji Generator (Searcher)/index.html
Labels: Level2, GSSoC22

#1334 Added Binary calculator
  Binary_Calculator/index.css
  Binary_Calculator/index.html
  Binary_Calculator/index.js
Labels: Level2, GSSoC22, ready-to-merge

#1338 Balloon Popping game
  balloon popping game/balloon-blue.png
  balloon popping game/balloon-green.png
  balloon popping game/balloon-red.png
  balloon popping game/balloon-violet.png
  balloon popping game/balloon-yellow.png
  balloon popping game/bg-music.mp3
  balloon popping game/happy.png
  balloon popping game/index.html
  balloon popping game/pop.mp3
  balloon popping game/sad.png
  balloon popping game/script.js
  balloon popping game/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1343 Music Player
  Spogify_Music_Player/index.html
  Spogify_Music_Player/preview.png
  Spogify_Music_Player/readme.md
  Spogify_Music_Player/script.js
  Spogify_Music_Player/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1349 Added Real Estate Website Template
  Real_Estate_Website/img/home-bg.jpg
  Real_Estate_Website/img/home.jpg
  Real_Estate_Website/img/icon-1.png
  Real_Estate_Website/img/icon-2.png
  Real_Estate_Website/img/icon-3.png
  Real_Estate_Website/img/img-1.jpg
  Real_Estate_Website/img/img-2.jpg
  Real_Estate_Website/img/img-3.jpg
  Real_Estate_Website/img/img-4.jpg
  Real_Estate_Website/img/img-5.jpg
  Real_Estate_Website/img/img-6.jpg
  Real_Estate_Website/img/pic-1.png
  Real_Estate_Website/img/pic-2.png
  Real_Estate_Website/img/pic-3.png
  Real_Estate_Website/img/pic-4.png
  Real_Estate_Website/img/s-1.png
  Real_Estate_Website/img/s-2.png
  Real_Estate_Website/img/s-3.png
  Real_Estate_Website/index.html
  Real_Estate_Website/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1323 Architecture Website Design Template
  Architecture-Website/Readme.md
  Architecture-Website/images/JaneDoe.jpg
  Architecture-Website/images/MikeRoss.jpg
  Architecture-Website/images/about.png
  Architecture-Website/images/barn.jpg
  Architecture-Website/images/brickhose.jpg
  Architecture-Website/images/contact.png
  Architecture-Website/images/danStar.jpg
  Architecture-Website/images/homepage.jpg
  Architecture-Website/images/homepage.png
  Architecture-Website/images/johnDoe.jpg
  Architecture-Website/images/map.jpg
  Architecture-Website/images/projects.png
  Architecture-Website/images/renovated.jpg
  Architecture-Website/images/summerhose.jpg
  Architecture-Website/index.html
  Architecture-Website/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1318 Adding animated earth
  animated earth/images/earth-day.jpg
  animated earth/images/earth-night.jpg
  animated earth/index.html
  animated earth/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1325 Issue #1320 resolved: Cute Cat Dressing Room
  Cat Game/app.js
  Cat Game/index.html
  Cat Game/readme.md
  Cat Game/style.css
Labels: Level2, GSSoC22

#1350 Meme Generator using react
  meme-generator/README.md
  meme-generator/package.json
  meme-generator/public/index.html
  meme-generator/src/App.js
  meme-generator/src/components/Header.jsx
  meme-generator/src/components/MemeComponent.jsx
  meme-generator/src/components/assets/Troll Face.png
  meme-generator/src/components/styles/meme.css
  meme-generator/src/index.js
Labels: GSSoC22, Level3, ready-to-merge

#1340 DOM Object Manipulator
  DOM object manipulator/index.html
  DOM object manipulator/script.js
  DOM object manipulator/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1359 Space drifter
  space-drifter/README.md
  space-drifter/assets/asteroid-big.svg
  space-drifter/assets/asteroid-medium.svg
  space-drifter/assets/asteroid-small.svg
  space-drifter/assets/space-drifter-cover.jpg
  space-drifter/assets/stars.png
  space-drifter/assets/starship.svg
  space-drifter/assets/torpedo.svg
  space-drifter/game.js
  space-drifter/index.html
  space-drifter/styles.css
Labels: Level2, GSSoC22, ready-to-merge

#1360 Added notes taking website
  Notes_taking_website/img.png
  Notes_taking_website/magicnotes.html
  Notes_taking_website/magisnotes.js
Labels: Level2, GSSoC22, ready-to-merge

#1358 Added Finder site
  finder/Log In/images/bgimg.jpg
  finder/Log In/images/bglogin.jpg
  finder/Log In/images/facebook.png
  finder/Log In/images/instagram.png
  finder/Log In/images/linkedin.png
  finder/Log In/images/logotinder.png
  finder/Log In/images/twitter.png
  finder/Log In/index.html
  finder/Log In/script.js
  finder/Log In/style.css
  finder/Product/index.html
  finder/Product/style.css
  finder/README.md
  finder/css/img/background.png
  finder/css/img/down-arrow.png
  finder/css/img/logo.png
  finder/css/img/logotinder.png
  finder/index.html
  finder/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1381 furniture store website
  furniture store/.eslintrc.json
  furniture store/.gitignore
  furniture store/components/About.js
  furniture store/components/AboutCard.js
  furniture store/components/Client.js
  furniture store/components/Clients.js
  furniture store/components/Companies.js
  furniture store/components/Deal.js
  furniture store/components/Deals.js
  furniture store/components/Footer.js
  furniture store/components/Header.js
  furniture store/components/HeroHome.js
  furniture store/components/Product.js
  furniture store/components/Products.js
  furniture store/components/Sidebar.js
  furniture store/components/icons.js
  furniture store/next.config.js
  furniture store/package.json
  furniture store/pages/_app.js
  furniture store/pages/api/hello.js
  furniture store/pages/index.js
  furniture store/public/DOTS.svg
  furniture store/public/Dealimage.png
  furniture store/public/circle-pattern.svg
  furniture store/public/favicon.ico
  furniture store/public/logo-white.svg
  furniture store/public/logo.svg
  furniture store/public/logos/Business-web.svg
  furniture store/public/logos/Entrepreneur.svg
  furniture store/public/logos/Fortune.svg
  furniture store/public/logos/Mashable.svg
  furniture store/public/logos/Microsoft.svg
  furniture store/styles/globals.css
Labels: GSSoC22, Level3, ready-to-merge

#1380 Added PostMaster website
  PostMaster/index.html
  PostMaster/index.js
  PostMaster/logo.png
  PostMaster/prism.css
  PostMaster/prism.js
Labels: GSSoC22, Level3, ready-to-merge

#1383 Speech Command Listener
  speech command listener/index.html
  speech command listener/script.js
  speech command listener/style.css
  speech command listener/values.json
Labels: GSSoC22, Level3, ready-to-merge

#1385 Email Extractor
  Email Extractor/index.html
  Email Extractor/readme.md
Labels: Level2, GSSoC22, ready-to-merge

#1388 Added covid-19 website
  covid_19_information/css/contact.css
  covid_19_information/css/style.css
  covid_19_information/css/vaccine.css
  covid_19_information/img/logo.jpeg
  covid_19_information/img/logo2.jpg
  covid_19_information/img/service.jpg
  covid_19_information/img/vaccine2.jpg
  covid_19_information/index.html
  covid_19_information/static/service.html
  covid_19_information/static/vaccine.html
Labels: Level2, GSSoC22, ready-to-merge

#1379 Find me
  Find Me/index.html
  Find Me/readme.md
Labels: Level2, ready-to-merge

#1362 Added news taking website
  news_taking_website/ic2.jpg
  news_taking_website/index.html
  news_taking_website/index.js
  news_taking_website/logo2.webp
Labels: Level2, GSSoC22, ready-to-merge

#1372 Added Movie review website
  Movie info website/API_Information.txt
  Movie info website/Netflix-Intro-Sound-Effect.mp3
  Movie info website/Sub-Urban.mp3
  Movie info website/chevron-back-outline.svg
  Movie info website/chevron-forward-outline.svg
  Movie info website/close-circle-outline.svg
  Movie info website/favicon.png
  Movie info website/index.html
  Movie info website/menu-outline.svg
  Movie info website/movie.html
  Movie info website/moviescript.js
  Movie info website/profile.png
  Movie info website/script.js
  Movie info website/style.css
Labels: Level2, GSSoC22

#1368 Added digital calculator
  digital_calculator/images.png
  digital_calculator/index.html
  digital_calculator/index.js
  digital_calculator/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1378 Added Quiz app
  Quiz_App/package-lock.json
  Quiz_App/package.json
  Quiz_App/public/favicon.ico
  Quiz_App/public/index.html
  Quiz_App/public/logo192.png
  Quiz_App/public/logo512.png
  Quiz_App/public/manifest.json
  Quiz_App/public/robots.txt
  Quiz_App/src/App.css
  Quiz_App/src/App.js
  Quiz_App/src/App.test.js
  Quiz_App/src/components/End.js
  Quiz_App/src/components/Modal.js
  Quiz_App/src/components/Question.js
  Quiz_App/src/components/Start.js
  Quiz_App/src/data/quiz.json
  Quiz_App/src/index.js
  Quiz_App/src/reportWebVitals.js
  Quiz_App/src/setupTests.js
  Quiz_App/src/utils/index.js
Labels: GSSoC22, Level3, ready-to-merge

#1376 Pacman game
  Pacman/README.md
  Pacman/favicon.png
  Pacman/game.js
  Pacman/index.html
  Pacman/index.js
Labels: GSSoC22, Level3, ready-to-merge

#1387 Added Drag and Drop website
  drag_and_drop/index.html
  drag_and_drop/index.js
  drag_and_drop/rose.jpg
  drag_and_drop/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1354 Menu
  Side Menu/index.html
  Side Menu/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1417 Main website UI and added all projects
  index.html
  style.css
Labels: GSSoC22, Level3

#1410 Plagiarism Checker App added
  Plagiarism Checker/README.md
  Plagiarism Checker/package.json
  Plagiarism Checker/public/favicon.ico
  Plagiarism Checker/public/index.html
  Plagiarism Checker/public/logo192.png
  Plagiarism Checker/public/logo512.png
  Plagiarism Checker/public/manifest.json
  Plagiarism Checker/public/robots.txt
  Plagiarism Checker/src/App.css
  Plagiarism Checker/src/App.js
  Plagiarism Checker/src/App.test.js
  Plagiarism Checker/src/components/CodeForm/index.js
  Plagiarism Checker/src/index.css
  Plagiarism Checker/src/index.js
  Plagiarism Checker/src/logo.svg
  Plagiarism Checker/src/serviceWorker.js
  Plagiarism Checker/src/setupTests.js
Labels: GSSoC22, Level3, ready-to-merge

#1392 Skype Clone
  Skype Clone/.gitignore
  Skype Clone/README.md
  Skype Clone/package.json
  Skype Clone/public/favicon.ico
  Skype Clone/public/index.html
  Skype Clone/public/logo192.png
  Skype Clone/public/logo512.png
  Skype Clone/public/manifest.json
  Skype Clone/public/robots.txt
  Skype Clone/src/App.test.js
  Skype Clone/src/Reducers/activeUserIdReducer.js
  Skype Clone/src/Reducers/contacts.js
  Skype Clone/src/Reducers/index.js
  Skype Clone/src/Reducers/messages.js
  Skype Clone/src/Reducers/typing.js
  Skype Clone/src/Reducers/userReducer.js
  Skype Clone/src/Store/store.js
  Skype Clone/src/actions/constants/action-type.js
  Skype Clone/src/actions/index.js
  Skype Clone/src/component/ChatWindow.css
  Skype Clone/src/component/ChatWindow.js
  Skype Clone/src/component/Chats.css
  Skype Clone/src/component/Chats.js
  Skype Clone/src/component/Empty.css
  Skype Clone/src/component/Empty.js
  Skype Clone/src/component/Header.css
  Skype Clone/src/component/Header.js
  Skype Clone/src/component/Main.css
  Skype Clone/src/component/Main.js
  Skype Clone/src/component/MessageInput.css
  Skype Clone/src/component/MessageInput.js
  Skype Clone/src/component/Sidebar.css
  Skype Clone/src/component/Sidebar.js
  Skype Clone/src/containers/App.css
  Skype Clone/src/containers/App.js
  Skype Clone/src/containers/User.css
  Skype Clone/src/containers/User.js
  Skype Clone/src/index.css
  Skype Clone/src/index.js
  Skype Clone/src/logo.svg
  Skype Clone/src/serviceWorker.js
  Skype Clone/src/setupTests.js
  Skype Clone/src/static-data.js
Labels: GSSoC22, Level3

#1384 Unsplash Clone
  Unsplash Clone/README.md
  Unsplash Clone/package.json
  Unsplash Clone/public/index.html
  Unsplash Clone/public/manifest.json
  Unsplash Clone/src/App.js
  Unsplash Clone/src/components/Categories.js
  Unsplash Clone/src/components/Header.js
  Unsplash Clone/src/components/Hero.js
  Unsplash Clone/src/components/Image.js
  Unsplash Clone/src/css/App.css
  Unsplash Clone/src/css/Catergories.css
  Unsplash Clone/src/css/Header.css
  Unsplash Clone/src/css/Hero.css
  Unsplash Clone/src/css/Image.css
  Unsplash Clone/src/css/ImageGrid.css
  Unsplash Clone/src/css/index.css
  Unsplash Clone/src/index.js
  Unsplash Clone/src/pages/HomePage.js
  Unsplash Clone/src/pages/SearchPage.js
  Unsplash Clone/src/unsplash.js
Labels: GSSoC22, Level3

#1428 Markdown IDE
  Markdown IDE/README.md
  Markdown IDE/package.json
  Markdown IDE/public/favicon.ico
  Markdown IDE/public/index.html
  Markdown IDE/public/manifest.json
  Markdown IDE/src/index.css
  Markdown IDE/src/index.js
Labels: Level2, GSSoC22

#1451 Added chess game
  Chess_Game/img/bg-mobile.jpg
  Chess_Game/img/bg.jpg
  Chess_Game/index.html
  Chess_Game/script.js
  Chess_Game/style.css
Labels: GSSoC22, Level3

#1442 DnD-Dashboard or Trello Clone using React DnD
  DnD-Dashboard/README.md
  DnD-Dashboard/built/404.html
  DnD-Dashboard/built/index.html
  DnD-Dashboard/client/src/App.jsx
  DnD-Dashboard/client/src/components/Col.jsx
  DnD-Dashboard/client/src/components/DropWrapper.jsx
  DnD-Dashboard/client/src/components/Header.jsx
  DnD-Dashboard/client/src/components/Item.jsx
  DnD-Dashboard/client/src/components/Window.jsx
  DnD-Dashboard/client/src/data/index.js
  DnD-Dashboard/client/src/data/types.js
  DnD-Dashboard/client/src/index.js
  DnD-Dashboard/client/src/pages/Homepage.jsx
  DnD-Dashboard/client/style/index.css
  DnD-Dashboard/client/templates/index.ejs
  DnD-Dashboard/package-lock.json
  DnD-Dashboard/package.json
  DnD-Dashboard/server/index.js
  DnD-Dashboard/webpack.config.js
  DnD-Dashboard/yarn.lock
Labels: GSSoC22, Level3, ready-to-merge

#1439 Added Spy Number Checker
  Spy Number Checker/Readme.md
  Spy Number Checker/index.html
  Spy Number Checker/script/script.js
  Spy Number Checker/snips/snip1.png
  Spy Number Checker/style/style.css
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1473 Restaurant Landing Page
  Restuarant Landing Page/README.md
  Restuarant Landing Page/index.html
  Restuarant Landing Page/style.css
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1399 Pokemon Memory Card Game using ReactJS
  Pokemon Memory card Game/README.md
  Pokemon Memory card Game/package.json
  Pokemon Memory card Game/public/img/angular.png
  Pokemon Memory card Game/public/img/css.png
  Pokemon Memory card Game/public/img/html.png
  Pokemon Memory card Game/public/img/js.png
  Pokemon Memory card Game/public/img/nodejs.png
  Pokemon Memory card Game/public/img/react.png
  Pokemon Memory card Game/public/img/scss.png
  Pokemon Memory card Game/public/img/vue.png
  Pokemon Memory card Game/public/index.html
  Pokemon Memory card Game/public/logo192.png
  Pokemon Memory card Game/public/logo512.png
  Pokemon Memory card Game/src/App.js
  Pokemon Memory card Game/src/components/Card.js
  Pokemon Memory card Game/src/components/Cards.js
  Pokemon Memory card Game/src/index.css
  Pokemon Memory card Game/src/index.js
Labels: GSSoC22, Level3, ready-to-merge

#1224 Added Virtual Keyboard
  Virtual-Keyboard/README.md
  Virtual-Keyboard/vKeyboard.css
  Virtual-Keyboard/vKeyboard.html
  Virtual-Keyboard/vKeyboard.js
Labels: Level1, GSSoC22, ready-to-merge

#1464 Added Shopping Cart using TypeScript
  Shopping-Cart/README.md
  Shopping-Cart/package-lock.json
  Shopping-Cart/package.json
  Shopping-Cart/public/favicon.ico
  Shopping-Cart/public/index.html
  Shopping-Cart/public/logo192.png
  Shopping-Cart/public/logo512.png
  Shopping-Cart/public/manifest.json
  Shopping-Cart/public/robots.txt
  Shopping-Cart/src/App.styles.ts
  Shopping-Cart/src/App.tsx
  Shopping-Cart/src/Cart/Cart.styles.ts
  Shopping-Cart/src/Cart/Cart.tsx
  Shopping-Cart/src/CartItem/CartItem.styles.ts
  Shopping-Cart/src/CartItem/CartItem.tsx
  Shopping-Cart/src/Item/Item.styles.tsx
  Shopping-Cart/src/Item/Item.tsx
  Shopping-Cart/src/index.tsx
  Shopping-Cart/src/react-app-env.d.ts
  Shopping-Cart/tsconfig.json
  Shopping-Cart/yarn.lock
Labels: Level2, GSSoC22, ready-to-merge

#1465 feat: Face Detector added
  Face detection using JS/README.md.md
  Face detection using JS/face.html
  Face detection using JS/face.js
  Face detection using JS/styles.css
Labels: GSSoC22, Level3, ready-to-merge

#1405 Added world map
  world_map/data.json
  world_map/index.html
  world_map/index.js
Labels: Level1, GSSoC22

#1401 UPLOAD AND DISPLAYE
  Upload and Display/Readme.md
  Upload and Display/index.html
  Upload and Display/script.js
  Upload and Display/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1315 CSS Link & Readme in calculator
  Calculator/README.md
  Calculator/index.html
  Grocery store/readme.md
Labels: GSSoC22, ready-to-merge, Level0

#1429 Memory Game
  MemoryGame/index.html
  MemoryGame/preview.jpg
  MemoryGame/preview1.gif
  MemoryGame/script.js
  MemoryGame/style.css
Labels: Level2, GSSoC22, ready-to-merge

#1430 CSS Background
  Pure CSS Background Fruit/index.html
  Pure CSS Background Fruit/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1431 Loading Animation
  Loading Animation/index.html
  Loading Animation/preview3.gif
  Loading Animation/script.js
  Loading Animation/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1440 Searched and Get
  Searched and Get/Readme.md
  Searched and Get/index.html
  Searched and Get/script.js
  Searched and Get/style.css
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1441 Duration between two dates
  Duration during two dates/Readme.md
  Duration during two dates/index.html
  Duration during two dates/script.js
  Duration during two dates/style.css
Labels: enhancement, Level1, GSSoC22, ready-to-merge

#1481 Landing page template
  Landing_Page_Template/README.md
  Landing_Page_Template/assets/images/Desktop_view.png
  Landing_Page_Template/assets/images/Mobile_view.png
  Landing_Page_Template/assets/images/img-1.jpeg
  Landing_Page_Template/assets/images/img-2.jpeg
  Landing_Page_Template/assets/images/logo.jpeg
  Landing_Page_Template/assets/style.css
  Landing_Page_Template/index.html
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1434 5 Page responsive Insurance website
  Insurance Website/1.jpeg
  Insurance Website/2.jpeg
  Insurance Website/3.jpeg
  Insurance Website/4.jpeg
  Insurance Website/5.jpeg
  Insurance Website/Favicon.png
  Insurance Website/PHAM_Logo.png
  Insurance Website/Readme.md
  Insurance Website/TermsAndCondition.html
  Insurance Website/aboutUs.css
  Insurance Website/aboutUs.html
  Insurance Website/footer.css
  Insurance Website/footer.html
  Insurance Website/health.html
  Insurance Website/index.html
  Insurance Website/login.html
  Insurance Website/pic.jpeg
  Insurance Website/pics.jpeg
  Insurance Website/profile.css
  Insurance Website/profile.html
Labels: enhancement, GSSoC22, Level3, ready-to-merge

#1475 Chat App files added
  IChatApp WEBDEV/.gitignore
  IChatApp WEBDEV/icons8-chat.gif
  IChatApp WEBDEV/index.html
  IChatApp WEBDEV/js/client.js
  IChatApp WEBDEV/juntos-607.ogg
  IChatApp WEBDEV/nodeServer/index.js
  IChatApp WEBDEV/nodeServer/package-lock.json
  IChatApp WEBDEV/nodeServer/package.json
  IChatApp WEBDEV/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1476 player-bug-fixed
  Advance mp3 Player/script.js
Labels: Level1, GSSoC22

#1484 footer-contents-added
  Apple Website Clone/index.html
  Apple Website Clone/style/style.css
Labels: Level1, GSSoC22

#1485 Typing Speed Calculator
  42. Typing Speed Calculator/Typing_Speed.png
  42. Typing Speed Calculator/index.html
  42. Typing Speed Calculator/paragraphs.js
  42. Typing Speed Calculator/readme.md
  42. Typing Speed Calculator/script.js
  42. Typing Speed Calculator/style.css
  index.html
Labels: Level2, GSSoC22, ready-to-merge

#1487 Geeky Dev Blog Template
  Geeky Dev Blog template/README.md
  Geeky Dev Blog template/about.html
  Geeky Dev Blog template/assets/about 1.jfif
  Geeky Dev Blog template/assets/about 2.jfif
  Geeky Dev Blog template/assets/about 3.jfif
  Geeky Dev Blog template/assets/img 1.png
  Geeky Dev Blog template/assets/img 2.png
  Geeky Dev Blog template/assets/img 3.png
  Geeky Dev Blog template/assets/thumbnail 1.jpg
  Geeky Dev Blog template/assets/thumbnail 2.jpg
  Geeky Dev Blog template/assets/thumbnail 3.jpg
  Geeky Dev Blog template/assets/thumbnail 4.jpg
  Geeky Dev Blog template/contact.html
  Geeky Dev Blog template/index.html
  Geeky Dev Blog template/style.css
Labels: enhancement, GSSoC22, Level3, ready-to-merge

#1491 Plan Your Day using ReactJS
  Plan The Day/package.json
  Plan The Day/public/index.html
  Plan The Day/readme.md
  Plan The Day/src/App.css
  Plan The Day/src/App.js
  Plan The Day/src/App.test.js
  Plan The Day/src/Plan.js
  Plan The Day/src/index.css
  Plan The Day/src/index.js
  Plan The Day/src/reportWebVitals.js
  Plan The Day/src/setupTests.js
Labels: Level2, GSSoC22, ready-to-merge

#1489 Added CV Screener
  cv_screener/README.md
  cv_screener/index.html
  cv_screener/index.js
  cv_screener/ll.png
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1492 Birthday Reminder App added
  Birthday Reminder/README.md
  Birthday Reminder/package.json
  Birthday Reminder/public/favicon.ico
  Birthday Reminder/public/index.html
  Birthday Reminder/public/logo192.png
  Birthday Reminder/public/logo512.png
  Birthday Reminder/public/manifest.json
  Birthday Reminder/public/robots.txt
  Birthday Reminder/src/App.js
  Birthday Reminder/src/List.js
  Birthday Reminder/src/data.js
  Birthday Reminder/src/index.css
  Birthday Reminder/src/index.js
Labels: Level2, GSSoC22, request-changes

#1490 Added Sign In page
  sign_in_page/README.md
  sign_in_page/bg.jpeg
  sign_in_page/index.html
  sign_in_page/ll.png
  sign_in_page/style.css
Labels: Level1, GSSoC22, ready-to-merge

#1496 Phone Number Locator added
  Phone Number Locator/README.md
  Phone Number Locator/logo.png
  Phone Number Locator/popup.html
  Phone Number Locator/script.js
  Phone Number Locator/styles.css
Labels: enhancement, GSSoC22, Level3

#1498 3dbackground
  3D Environment/index.html
  3D Environment/preview.mp4
  3D Environment/script.js
  3D Environment/style.css
Labels: Level1, GSSoC22

#1501 adding ball animation
  Ball animation/index.html
  Ball animation/style.css
Labels: Level1, GSSoC22

#1500 Pool game
  Pool Game/8 ball pool.html
  Pool Game/Ball.js
  Pool Game/Canvas.js
  Pool Game/Color.js
  Pool Game/Constants.js
  Pool Game/Game.js
  Pool Game/GameWorld.js
  Pool Game/README.md
  Pool Game/Stick.js
  Pool Game/Tools.js
  Pool Game/Tools/black_ball.png
  Pool Game/Tools/red_ball.png
  Pool Game/Tools/stick.png
  Pool Game/Tools/table.png
  Pool Game/Tools/white_ball.png
  Pool Game/Tools/yellow_ball.png
  Pool Game/Vector2.js
  Pool Game/input/ButtonState.js
  Pool Game/input/Mouse.js
Labels: enhancement, Level2, GSSoC22, ready-to-merge

#1507 Hotstar UI CLone
  HotStar UI CLone/README.md
  HotStar UI CLone/assests/365ep.jpg
  HotStar UI CLone/assests/365ep.png
  HotStar UI CLone/assests/camera.jpg
  HotStar UI CLone/assests/sci-fi.png
  HotStar UI CLone/index.html
  HotStar UI CLone/movies.css
  HotStar UI CLone/movies.html
  HotStar UI CLone/movies.js
  HotStar UI CLone/script.js
  HotStar UI CLone/style.css
Labels: GSSoC22, Level3

#1462 Double Vertical Image Slider
  Double_Vertical_Slider/img/img1.jpg
  Double_Vertical_Slider/img/img2.jpg
  Double_Vertical_Slider/img/img3.jpg
  Double_Vertical_Slider/img/img4.jpg
  Double_Vertical_Slider/index.html
  Double_Vertical_Slider/script.js
  Double_Vertical_Slider/style.css
Labels: GSSoC22, Level3, ready-to-merge

#1506 Adding random wave
  Random wave/index.html
  Random wave/script.js
  Random wave/style.css
Labels: Level1, GSSoC22

#1529 Custom Error Page
  Custom Error Page/README.md
  Custom Error Page/next-env.d.ts
  Custom Error Page/next.config.js
  Custom Error Page/package.json
  Custom Error Page/public/favicon.ico
  Custom Error Page/public/vercel.svg
  Custom Error Page/src/errors/Customerror.ts
  Custom Error Page/src/pages/_app.tsx
  Custom Error Page/src/pages/articles/post.tsx
  Custom Error Page/src/pages/error.tsx
  Custom Error Page/src/pages/index.tsx
  Custom Error Page/styles/Home.module.css
  Custom Error Page/styles/globals.css
  Custom Error Page/tsconfig.json
  cv_screener/README.md
  cv_screener/index.html
Labels: enhancement, GSSoC22, Level3, ready-to-merge

#1540 Added Evil Number Checker
  Evil Number Checker/Readme.md
  Evil Number Checker/index.html
  Evil Number Checker/script/script.js
  Evil Number Checker/snips/snip1.png
  Evil Number Checker/style/style.css
Labels: Level2, GSSoC22

#1521 Flappy Bird
  Flappy Bird 2.0/index.html
  Flappy Bird 2.0/readme.md
Labels: g1j

#1553 Added TinDogWebsite
  TinDogWebsite/README.md
  TinDogWebsite/css/styles.css
  TinDogWebsite/images/DS_Store.txt
  TinDogWebsite/images/TechCrunch.png
  TinDogWebsite/images/bizinsider.png
  TinDogWebsite/images/dog-img.jpg
  TinDogWebsite/images/iphone6.png
  TinDogWebsite/images/lady-img.jpg
  TinDogWebsite/images/mashable.png
  TinDogWebsite/images/tnw.png
  TinDogWebsite/index.html
Labels: GSSoC22, Level3

#1446 GK FlipBook files added
  GK FlipBook/README.md
  GK FlipBook/index.html
  GK FlipBook/pics.json
  GK FlipBook/script.js
  GK FlipBook/style.css
Labels: enhancement, Level2

#1532 Memento
  anime_card_game/images/aot_pose.jpeg
  anime_card_game/images/aot_wall.jpeg
  anime_card_game/images/code_geass_chess.jpeg
  anime_card_game/images/deathnote.jpeg
  anime_card_game/images/demon_slayer.jpeg
  anime_card_game/images/don_luffy.jpeg
  anime_card_game/images/luffy.jpeg
  anime_card_game/images/one_punchman.jpeg
  momentos/client/.gitignore
  momentos/client/package.json
  momentos/client/public/favicon.ico
  momentos/client/public/index.html
  momentos/client/public/manifest.json
  momentos/client/src/App.css
  momentos/client/src/App.js
  momentos/client/src/App.test.js
  momentos/client/src/actions/index.js
  momentos/client/src/components/AddModal.js
  momentos/client/src/components/Dashboard.js
  momentos/client/src/components/Modal.js
  momentos/client/src/components/Navbar.js
  momentos/client/src/components/Portal.js
  momentos/client/src/components/Todo.js
  momentos/client/src/index.css
  momentos/client/src/index.js
  momentos/client/src/registerServiceWorker.js
  momentos/models/Memories.js
  momentos/models/User.js
  momentos/package.json
  momentos/readme.md
  momentos/routes/authRoute.js
  momentos/routes/memories.js
  momentos/server.js
  momentos/services/passport.js
Labels: GSSoC22, Level3

#1474 Plots Availability checker files added
  Plot Viewer/README.md
  Plot Viewer/Screenshot (268).png
  Plot Viewer/aerial.jpg
  Plot Viewer/drawing.svg
  Plot Viewer/index.html
  Plot Viewer/loacation icon.png
  Plot Viewer/svg.html
Labels: enhancement, GSSoC22, Level3, ready-to-merge

#1448 Learner's Playground files added
  Learner's playground/README.md
  Learner's playground/antonyms.html
  Learner's playground/antonyms.txt
  Learner's playground/antonyms_background.jpg
  Learner's playground/english.js
  Learner's playground/fish.gif
  Learner's playground/frog.gif
  Learner's playground/skip.gif
  Learner's playground/synonyms.css
Labels: enhancement, Level2, GSSoC22

#1555 Added TimelineJS
  TimelineJS/.gitignore
  TimelineJS/README.md
  TimelineJS/index.html
  TimelineJS/main.js
  TimelineJS/style.css
  TimelineJS/timeline-preview.png
Labels: Level2, GSSoC22, ready-to-merge

#1556 Added URL-SHORTENER
  URLSHORTENER/.eslintrc.json
  URLSHORTENER/.github/FUNDING.yml
  URLSHORTENER/.gitignore
  URLSHORTENER/README.md
  URLSHORTENER/api/controllers/UrlController.js
  URLSHORTENER/api/helpers/base58.js
  URLSHORTENER/api/models/Url.js
  URLSHORTENER/config/env/development.js
  URLSHORTENER/config/env/index.js
  URLSHORTENER/config/env/production.js
  URLSHORTENER/config/env/test.js
  URLSHORTENER/config/express.js
  URLSHORTENER/config/routes/index.js
  URLSHORTENER/config/routes/url.js
  URLSHORTENER/config/sequelize.js
  URLSHORTENER/index.js
  URLSHORTENER/package-lock.json
  URLSHORTENER/package.json
  URLSHORTENER/screenshot.png
  URLSHORTENER/test/url.test.js
  URLSHORTENER/view/css/styles.css
  URLSHORTENER/view/index.html
  URLSHORTENER/view/javascript/shorten.js
Labels: GSSoC22, Level3, ready-to-merge

#1502 Added Responsive Multi-functionality notes app
  Multi-functioned Notes App/Readme.md
  Multi-functioned Notes App/index.css
  Multi-functioned Notes App/index.html
  Multi-functioned Notes App/index.js
Labels: Level2, GSSoC22

#1548 Missile game
  Missile Game/README.md
  Missile Game/asteroid.js
  Missile Game/asteroid.svg
  Missile Game/background.svg
  Missile Game/index.html
  Missile Game/main.js
  Missile Game/ship.js
  Missile Game/ship.svg
Labels: Level2, GSSoC22

#1557 Added DrawJS
  DrawJS/.gitignore
  DrawJS/README.md
  DrawJS/bg-image.jpg
  DrawJS/color-palette.png
  DrawJS/eraser.svg
  DrawJS/index.html
  DrawJS/pencil.png
  DrawJS/preview.png
  DrawJS/preview_2.png
  DrawJS/script.js
  DrawJS/style.css
Labels: Level2, GSSoC22

#1508 Whiteboard
  WhiteBoard/index.html
  WhiteBoard/script.js
  WhiteBoard/style.css
Labels: Level2, GSSoC22

#1558 Added ManageCloudWebsite
  ManageCloudApp/.gitignore
  ManageCloudApp/1.png
  ManageCloudApp/2.png
  ManageCloudApp/3.png
  ManageCloudApp/4.png
  ManageCloudApp/README.md
  ManageCloudApp/client/package.json
  ManageCloudApp/client/public/favicon.ico
  ManageCloudApp/client/public/index.html
  ManageCloudApp/client/public/logo192.png
  ManageCloudApp/client/public/logo512.png
  ManageCloudApp/client/public/manifest.json
  ManageCloudApp/client/public/robots.txt
  ManageCloudApp/client/src/App.css
  ManageCloudApp/client/src/App.js
  ManageCloudApp/client/src/components/auth/Login.js
  ManageCloudApp/client/src/components/auth/Register.js
  ManageCloudApp/client/src/components/contacts/ContactForm.js
  ManageCloudApp/client/src/components/contacts/ContactItem.js
  ManageCloudApp/client/src/components/contacts/Contacts.js
  ManageCloudApp/client/src/components/contacts/FilterContacts.js
  ManageCloudApp/client/src/components/layout/Alerts.js
  ManageCloudApp/client/src/components/layout/Navbar.js
  ManageCloudApp/client/src/components/pages/About.js
  ManageCloudApp/client/src/components/pages/Home.js
  ManageCloudApp/client/src/components/routing/PrivateRoute.js
  ManageCloudApp/client/src/index.js
  ManageCloudApp/client/src/store/actions/alert/index.js
  ManageCloudApp/client/src/store/actions/auth/index.js
  ManageCloudApp/client/src/store/actions/contacts/index.js
  ManageCloudApp/client/src/store/reducers/alert/index.js
  ManageCloudApp/client/src/store/reducers/auth/index.js
  ManageCloudApp/client/src/store/reducers/contacts/index.js
  ManageCloudApp/client/src/store/reducers/rootReducer.js
  ManageCloudApp/client/src/store/types.js
  ManageCloudApp/client/src/utils/setAuthToken.js
  ManageCloudApp/config/db.js
  ManageCloudApp/config/default.json
  ManageCloudApp/config/production.json
  ManageCloudApp/middleware/auth.js
  ManageCloudApp/models/Contact.js
  ManageCloudApp/models/User.js
  ManageCloudApp/package.json
  ManageCloudApp/routes/auth.js
  ManageCloudApp/routes/contacts.js
  ManageCloudApp/routes/users.js
  ManageCloudApp/server.js
Labels: GSSoC22, Level3

#1560 Added RandomQuoteGen
  RandomQuoteGen/.gitignore
  RandomQuoteGen/1.png
  RandomQuoteGen/README.md
  RandomQuoteGen/css/normalize.css
  RandomQuoteGen/css/styles.css
  RandomQuoteGen/favicon.ico
  RandomQuoteGen/index.html
  RandomQuoteGen/js/script.js
Labels: Level2, GSSoC22

#1566 Rockstar page
  Rockstar page/README.md
  Rockstar page/assets/bootstrap/css/bootstrap.min.css
  Rockstar page/assets/bootstrap/js/bootstrap.min.js
  Rockstar page/assets/img/girlgit.jpg
  Rockstar page/assets/img/git1.jpg
  Rockstar page/assets/img/gituar3.jpg
  Rockstar page/index.html
Labels: GSSoC22, Level3

#1545 Business header page
  Business header page/Business-English-Pod-Learn-Business-English.jpg
  Business header page/README.md
  Business header page/desk-3139127_1920-1200x773.jpg
  Business header page/index.html
Labels: Level2, GSSoC22
